<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$pricesubmission = new CommodityPriceSubmission();
	
	// default title is to enable adding any payee
	$title = $this->translate("commodityprice_chemical_pagetitle_view"); 
	$pricesubmission->populate(decode($request->id));
		
	$this->headTitle($title);	
	
?>
<script>
	$(document).ready(function() {		
		$(".delete").click(function(){
			if(window.confirm("Are you sure you want to Delete all prices for this Submission? \n Click OK to confirm or Cancel to stay on this page.")){
				return true;
			} else {
				return false;
			}
		}); 
		
		// filter the categories and display only commodities of a certain category
		$("#categoryid").change(function(){
			// alert("value is "+this.value);
			if(this.value == ""){
				$("table.commodities tbody tr").show();
			} else {
				$("table.commodities tbody tr").not("."+this.value).hide();
				$("table.commodities tbody tr."+this.value).show();
			}
		});
		
		// Copy buttons at the top to the bottom
		$("td.bottombuttons").html($("td.topbuttons").html());
	}); 
</script>

<form>
  <div class="pageinfo"><?php echo $this->translate("commodityprice_chemical_create_info"); ?></div>
  <table class="formtable">
    <tfoot>
      <tr>
        <td class="topbuttons">
		<?php if ($acl->checkPermission('Agricultural Chemical', ACTION_DELETE)) { ?>          	
          	<a href="<?php echo $this->baseUrl('agriculturalchemical/delete/entityname/CommodityPriceSubmission/id/'.encode($pricesubmission->getID()).'/'.SUCCESS_MESSAGE.'/Prices has been successfully deleted/'.URL_SUCCESS.'/'.encode($this->baseUrl("agriculturalchemical/list"))); ?>" class="negativeaction delete" title="<?php echo $this->translate("commodityprice_button_delete"); ?>"><img src="<?php echo $this->baseUrl('images/cross.png'); ?>" /><?php echo $this->translate("commodityprice_button_delete"); ?></a>&nbsp;&nbsp;
        <?php } ?>
		<?php if ($acl->checkPermission('Agricultural Chemical', ACTION_EDIT)) { ?>
          <a href="<?php echo $this->baseUrl('agriculturalchemical/index/id/'.encode($pricesubmission->getID())); ?>" class="positiveaction" title="<?php echo $this->translate("commodityprice_update_button_edit"); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>" /><?php echo $this->translate("commodityprice_update_button_edit"); ?></a>&nbsp;&nbsp;
        <?php } ?>         
        <?php if ($acl->checkPermission('Agricultural Chemical', ACTION_LIST)) { ?>
          <a href="<?php echo $this->baseUrl('agriculturalchemical/list'); ?>" class="positiveaction" title="<?php echo $this->translate("commodityprice_button_list"); ?>"><img src="<?php echo $this->baseUrl('images/arrow_undo.png'); ?>" /><?php echo $this->translate("commodityprice_button_list"); ?></a>&nbsp;&nbsp;
        <?php } ?></td>
      </tr>
    </tfoot>
  </table>
  <br />
  <?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
  <div class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
  <?php } ?>
  <table class="formtable">
    <tr class="sectionheading">
      <td colspan="2"><?php echo $title; ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("commodityprice_datecollected_label"); ?>:</td>
      <td><?php echo changeMySQLDateToPageFormat($pricesubmission->getDateCollected()); ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("commodityprice_chemical_location_label"); ?>:</td>
      <td><?php echo $pricesubmission->getSource()->getLocation()->getName(); ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("commodityprice_collectedby_label"); ?>:</td>
      <td><?php echo $pricesubmission->getCollectedBy()->getName(); ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("commodityprice_status_label"); ?>:</td>
      <td><?php echo $pricesubmission->getStatus(); ?></td>
    </tr>
  </table>
  <br />
  <table class="formtable commodities">
    <thead>
      <tr class="sectionheading">
        <td align="left" class="nowrapping" style="width:260px;">Commodity<?php echo $this->translate("commodityprice_commodity_label"); ?></td>
        <td align="center"><?php echo $this->translate("commodityprice_units_label"); ?></td>
        <td align="center"><?php echo 'Wholesale'/*$this->translate("commodityprice_wholesale_label")*/; ?></td>
        <td align="center"><?php echo 'Retail'/*$this->translate("commodityprice_retail_label")*/; ?></td>        
        <td align="center">Notes</td>
      </tr>
    </thead>
    <?php   
  		# Fetch Existing Price Details for the current submission
		$commodities = $pricesubmission->getCurrentPriceDetails(6);
		// debugMessage($result);
		$i = 0;
		foreach($commodities as $commodity){
  ?>
    <tr class="<?php echo $commodity['categoryid']; ?>">
      <td align="left" class="label"><?php echo $commodity['name']; ?></td>
      <td align="center"><?php echo $commodity['units']; ?></td>
      <td align="center" class="prices"><?php echo formatNumber($commodity['wholesaleprice']); ?></td>
      <td align="center" class="prices"><?php echo formatNumber($commodity['retailprice']); ?></td>
      <td align="center"><script>
			$(document).ready(function(){				
				
				$("#notes_<?php echo $i; ?>_trigger").click(function(){					
					$("#dialog_<?php echo $i; ?>").dialog({
						width: 500,
						height: 200,
						show: 'slide',						
						modal: true,
						title: $(this).attr('title'),						
						buttons: [{text: "Ok", click: function() { $(this).dialog("close"); }}] 
					});
				});
			});
		</script>
        <?php if(isEmptyString($commodity['notes'])){ ?>
        ---
        <?php } else { ?>
        <a href="javascript: doNothing();" class="notes" id="notes_<?php echo $i; ?>_trigger" title="Notes for <?php echo $commodity['name']; ?>"><img src="<?php echo $this->baseUrl('images/notes_plus.png'); ?>" /></a>
        <div id="dialog_<?php echo $i; ?>" class="hidden" style="width:500px; height:250px;">
          <label><?php echo nl2br($commodity['notes']); ?></label>
        </div>
        <?php } ?></td>
    </tr>
    <?php $i++;
	 }	
	?>
  </table>
  <br />
  <table class="formtable">
    <thead>
      <tr class="sectionheading">
        <td><?php echo $this->translate("commodityprice_comments_label"); ?></td>
      </tr>
    </thead>
    <tr>
      <td><?php echo nl2br($pricesubmission->getComments()); ?></td>
    </tr>
  </table>
  <table class="formtable <?php echo $hide_on_print_class; ?> formactions">
    <tfoot>
      <tr>
        <td class="bottombuttons"></td>
      </tr>
    </tfoot>
  </table>
</form>
<?php
	$session->setVar(SUCCESS_MESSAGE, "");
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
