<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$district = new District(); 
	
	// default title is to enable adding any payee
	$title = $this->translate("district_pagetitle_new"); 
	$posturl = $this->baseUrl("district/create");
	$button_title = $this->translate("district_button_new"); 
	
	// set the payee if provided in the url 
	if (!isEmptyString($request->id)) {
		$district->populate(decode($request->id));
		$title = sprintf($this->translate("district_pagetitle_edit"), $district->getName()); 
		$button_title = $this->translate("district_button_edit");
		$posturl = $this->baseUrl("district/edit"); 
	}
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$district->processPost($session->getVar(FORM_VALUES));	
	}
	
	$this->headTitle($title);  
?>
<script>
	$(document).ready(function() {
		$("#regionform").validate({		
			// define the validation rules one field at a time
			rules: {
				regionid: "required",
				name: "required"
			}, 
			// the messages for each of the fields being validated
			messages: {				
				regionid: "<?php echo $this->translate("district_region_error"); ?>",
				name: "<?php echo $this->translate("district_name_error"); ?>"
			}
		});
	}); 
</script>

<div class="pageinfo"><?php echo $this->translate("district_page_info"); ?></div>
<form id="regionform" action="<?php echo $posturl; ?>" method="post">
  <table class="formtable">
    <tr class="sectionheading">
      <td colspan="2"><?php echo $title; ?></td>
    </tr>
    <?php if ($sessionhaserror) { ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="error"><?php echo $session->getVar(ERROR_MESSAGE); ?></td>
    </tr>
    <?php } ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="pagedescription"><?php echo $this->translate("required_field_info"); ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("district_region_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
      <td><?php
      	$regionlist = new LookupType(); 
      	$regionlist->setName("ALL_REGIONS");
       	$regiondropdown = new Zend_Form_Element_Select('regionid',
							array(
								'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $regionlist->getOptionValuesFromQuery()),								'view' => new Zend_View(),
								'decorators' => array('ViewHelper')
							)
						);
		$regiondropdown->setValue($district->getRegionID()); 
		echo $regiondropdown->render(); 
      ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("district_name_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
      <td><input type="text" name="name" id="name" value="<?php echo $district->getName(); ?>" /></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("district_description_label"); ?>:</td>
      <td><textarea class="expanding" id="description" name="description"><?php echo $district->getDescription(); ?></textarea></td>
    </tr>
  </table>
  <table class="formtable formactions">
    <tfoot>
      <tr>
        <td><a href="<?php echo $this->baseUrl("district/list"); ?>" title="Cancel">Cancel</a>&nbsp;&nbsp;
          <button type="submit" class="positiveaction" id="submit" name="submit" title="<?php echo $button_title; ?>"><img src="<?php echo $this->baseUrl("images/tick.png"); ?>" /><?php echo $button_title; ?></button>
          <input type="hidden" name="entityname" value="District" />
          <input type="hidden" id="id" name="id" value="<?php echo encode($district->getID()); ?>" /></td>
      </tr>
    </tfoot>
  </table>
</form>
<?php
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
