<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$district = new District();
	
	// default title is to enable adding any payee
	$title = $this->translate("district_pagetitle_view"); 
	$district->populate(decode($request->id));
		
	$this->headTitle($title);  
?>
<script>
	$(document).ready(function() {		
		$("table.formtable .delete").click(function(){
			if(window.confirm("Are you sure you want to Delete this District? \n Click OK to confirm or Cancel to stay on this page.")){
				return true;
			} else {
				return false;
			}
		}); 		
	}); 
</script>
<div class="pageinfo"><?php echo $this->translate("district_page_info"); ?></div>
<?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
<div class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
<?php } ?>
<table class="formtable">
  <tr class="sectionheading">
    <td colspan="2"><?php echo $title; ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("district_region_label"); ?>:</td>
    <td><?php echo $district->getRegion()->getName(); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("district_name_label"); ?>:</td>
    <td><?php echo $district->getName(); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("district_description_label"); ?>:</td>
    <td><?php echo $district->getDescription(); ?></td>
  </tr>  
</table>
<table class="formtable formactions">
  <tfoot>
    <tr>
      <td><?php if ($acl->checkPermission('District', ACTION_DELETE) || isLGMISAdmin()) { ?>
        <a href="<?php echo $this->baseUrl('district/delete/entityname/District/id/'.encode($district->getID()).'/'.SUCCESS_MESSAGE.'/District has been successfully deleted/'.URL_SUCCESS.'/'.encode($this->baseUrl("district/list"))); ?>" class="negativeaction delete" title="<?php echo $this->translate("district_button_delete"); ?>"><img src="<?php echo $this->baseUrl('images/cross.png'); ?>" /><?php echo $this->translate("district_button_delete"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('District', ACTION_EDIT) || isLGMISAdmin()) { ?>
        <a href="<?php echo $this->baseUrl('district/index/id/'.encode($district->getID())); ?>" class="positiveaction" title="<?php echo $this->translate("district_pagetitle_edit"); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>" /><?php echo $this->translate("district_pagetitle_edit"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('District', ACTION_LIST) || isLGMISAdmin()) { ?>
        <a href="<?php echo $this->baseUrl('district/list'); ?>" class="positiveaction" title="<?php echo $this->translate("district_button_list"); ?>"><img src="<?php echo $this->baseUrl('images/arrow_undo.png'); ?>" /><?php echo $this->translate("district_button_list"); ?></a>
        <?php } ?></td>
    </tr>
  </tfoot>
</table>
<?php
	$session->setVar(SUCCESS_MESSAGE, "");
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
