 <?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$logofilename = 'infotradelogo.png';
	$companyname = 'AGMIS';
	$typeclass = '';
	$title = 'AGMIS';
	$logout_url = 'user/logout';
	if (isApplicationAGMIS()) {
		$typeclass = 'agmis';
	}
	if (isApplicationLAMIS()) {
		$logofilename = $session->getVar('logo');
		$companyname = $session->getVar('organisationname');
		$typeclass = 'lamis';
		$title = 'LAMIS Dashboard';
	}
	if (isApplicationLGMIS()) {		
		$companyname = $this->translate('lgmis_name'); 
		$typeclass = 'lgmis';
		$logofilename = 'coatOfArms_2.gif';
		$title = 'LGMIS Dashboard';
		$logout_url = 'lgmis/logout';
	}
	
	$logo_path = $this->baseUrl('uploads/lamis/logos/'.$logofilename);
	if (isApplicationLGMIS()) {
		$logo_path = $this->baseUrl('images/'.$logofilename);
		$dashboardurl = 'dataentry';
	}
?>
 <div id="header" class="<?php echo $typeclass; ?>">
    <div id="logo">
        <img src="<?php echo $logo_path; ?>" alt="Home" />&nbsp;
        <h1 id="sitetitle">Republic of Uganda</h1>  
        <span class="logotext"><?php echo $companyname; ?></span>
    </div>
    
        <div id="headerright">
          <ul id="toplinks">
          <?php if (!isEmptyString($session->getVar('userid'))) { ?>
            <li><span class="toplinkspacer">|</span><a href="<?php echo $this->baseUrl($logout_url); ?>" title="Logout">Logout</a></li>
            <li><a href="<?php echo $this->baseUrl("profile/view/id/".encode($userid)); ?>" title="My Profile"><?php echo $session->getVar('firstname')." ".$session->getVar('lastname'); ?></a></li>        
            <?php echo $session->getVar("settingslink"); ?>
            <?php if (isApplicationLGMIS() ) { ?>
            	<li><a href="<?php echo $this->baseUrl("dataentry"); ?>" title="LGMIS Dashboard">Dashboard</a><span class="toplinkspacer">|</span></li>
                <li><a href="<?php echo $this->baseUrl("lgmis"); ?>" title="Portal Home">Portal Home</a><span class="toplinkspacer">|</span></li>
            <?php } ?>     
    	  <?php } ?>
          <?php if (isEmptyString($session->getVar('userid')) && isApplicationLGMIS() && $request->getControllerName() == 'lgmis' ) { ?>
            <li><a href="<?php echo $this->baseUrl("lgmis/login"); ?>" title="Login">Login</a></li>
          <?php } ?>
          </ul>
          <?php if (isApplicationLAMIS() || isApplicationAGMIS()) { ?>
          	<div id="search"><input type="text" name="search" id="search" /></div>
          <?php } ?>   
          <?php if(isApplicationLGMIS() && $request->getControllerName() == 'lgmis' ) { ?>
              <div id="browse">
                <form method="get" id="searchform">
                <?php
                    $districtlist = new LookupType(); 
                    $districtlist->setName("AVAILABLE_LGMIS_DISTRICTS");
					// debugMessage($districtlist->getOptionValuesFromQuery());
                    $districtdropdown = new Zend_Form_Element_Select('browseid',
                        array(
                            'multiOptions' => array_merge_maintain_keys(array('' => 'Browse Districts'), $districtlist->getOptionValuesFromQuery()),								
                            'view' => new Zend_View(),
                            'decorators' => array('ViewHelper'),
                            'class' => array("filterselect", 'chzn-select'),
                        )
                    );
                    $districtdropdown->setValue($request->id); 
                    echo $districtdropdown->render(); 
                ?>
                </form>
              </div>
          <?php } ?>    
         
        </div>
  </div>
  <?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>