<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	# Page title
	$title = $this->translate("commodity_pagetitle_list");
	$this->headTitle($title);
	
	# Create an instance of the class to handle the pagination
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("c.name", "c.description", "cat.name"));
	$paginate->setFilterColumns(array("c.categoryid","cp.pricecategoryid"));
	$paginate->setDefaultSortBy("c.name");	

	$paginate->processPost($request->getParams());
	$all_results_query = "SELECT c.id, c.name as `Commodity`, cat.name as Category, c.description as Description, u.`name` as `Unit` FROM commodity c INNER JOIN commoditycategory cat ON c.categoryid = cat.id LEFT JOIN commodity p ON c.parentid = p.id LEFT JOIN commoditypricecategory as cp ON (c.id = cp.commodityid) LEFT JOIN commodityunit as u ON(c.unitid = u.id) WHERE c.name <> '' ".$paginate->getSearchAndFilterSQL()." GROUP BY c.id ".$paginate->getSortSQL();
	
	# debugMessage($all_results_query);
	$paginate->setItemCountFromSQLQuery($all_results_query);
	
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	//echo $current_results_query;
	$session->setVar(ALL_RESULTS_QUERY, $all_results_query);
	$session->setVar(CURRENT_RESULTS_QUERY, $current_results_query);
	# the query string to be appended to the return to list URL
	$session->setVar('list_query_string'.$request->getControllerName(), $request->getParams());
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
	# This variable stores the number of redundant columns returned in the query so that when we are printing
	# we are able to know how many columns to ignore. This variable is sent in the print URL
	$number_of_redundant_columns = 1;
	
	# the columns which contain numbers in the invoice query
	# Please note that the column count begins at 0
	$export_number_column_list = "";
?>

<form action="<?php echo $this->baseUrl("commodity/listsearch"); ?>" method="get" id="usersform">
  <table class="filtercontainer">
    <tr>
      <td><table class="filtersection">
          <tr>
            <td><?php
					$commoditycategorylist = new LookupType(); 
					$commoditycategorylist->setName("ALL_COMMODITY_CATEGORIES");
					$commoditycategorylistdropdown = new Zend_Form_Element_Select('c'.HTML_TABLE_COLUMN_SEPARATOR.'categoryid',
										array(
											'multiOptions' => array_merge_maintain_keys(array('' => 'All Categories'), $commoditycategorylist->getOptionValuesFromQuery()),								
											'view' => new Zend_View(),
											'decorators' => array('ViewHelper'),
											'class' => array('filterselect', 'chzn-select'),											
											'title' => 'Filter Commodities By Commodity Category'
										)
									);
					$commoditycategorylistdropdown->setValue($request->getParam('c'.HTML_TABLE_COLUMN_SEPARATOR.'categoryid')); 
					echo $commoditycategorylistdropdown->render(); 
				  ?>&nbsp;&nbsp;
                  <?php
					$pricecategorylist = new LookupType(); 
					$pricecategorylist->setName("ALL_PRICE_CATEGORIES");
					$pricecategorylistdropdown = new Zend_Form_Element_Select('cp'.HTML_TABLE_COLUMN_SEPARATOR.'pricecategoryid',
										array(
											'multiOptions' => array_merge_maintain_keys(array('' => 'All Price Types'), $pricecategorylist->getOptionValuesFromQuery()),										'view' => new Zend_View(),
											'decorators' => array('ViewHelper'),
											'class' => array('filterselect', 'chzn-select'),											
											'title' => 'Filter Commodities By Price Source'
										)
									);
					$pricecategorylistdropdown->setValue($request->getParam('cp'.HTML_TABLE_COLUMN_SEPARATOR.'pricecategoryid')); 
					echo $pricecategorylistdropdown->render(); 
				  ?>
                  </td>
          </tr>
          <tr>
            <td colspan="2"></td>
          </tr>
        </table></td>
      <td><table>
          <tr>
            <td><input class="filterselect" type="text" name="searchterm" id="searchterm" value="<?php echo $request->searchterm; ?>" title="Enter your search term here and click search" /></td>
          </tr>
          <tr>
            <td><button type="submit" class="positiveaction" id="searchbutton" title="Click here to Search or Filter"><img src="<?php echo $this->baseUrl("images/zoom_in.png"); ?>" alt="Search"/>Search</button></td>
          </tr>
        </table></td>
    </tr>
  </table>
  <?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
  <div class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
  <?php } ?>
  <?php // show a message that there are no items to display
	if ($has_no_data) {
?>
  <label class="error"><?php echo $this->translate("commodity_list_norecords"); ?></label>
  <?php } else { ?>
  <div id="counter"><?php echo sprintf($this->translate("commodity_list_counter"), $paginate->getItemCounterText()); ?></div>
  <div id="listcounter"><?php echo $this->listcountdropdown; ?></div>
  <div id="print"><a title="<?php echo $this->translate('global_print_as'); ?>" href="<?php echo $this->baseUrl('index/printerfriendly/'.EXPORT_NUMBER_COLUMN_LIST.'/'.$export_number_column_list.'/'.EXPORT_IGNORE_COLUMN_COUNT.'/'.$number_of_redundant_columns.'/'.PAGE_TITLE.'/'.$title); ?>" target="_blank"><?php echo $this->translate('global_print'); ?>&nbsp;<img src="<?php echo $this->baseUrl('images/printer.png'); ?>" alt="<?php echo $this->translate('global_print_as'); ?>" /></a></div>  
  <?php if ($acl->checkPermission('Commodity', ACTION_EXPORT) || isLGMISAdmin()) { ?>
  <div id="export"><a title="<?php echo $this->translate('global_export_as_excel'); ?>" href="<?php echo $this->baseUrl('index/exceldownload/'.EXPORT_NUMBER_COLUMN_LIST.'/'.$export_number_column_list.'/'.EXPORT_IGNORE_COLUMN_COUNT.'/'.$number_of_redundant_columns); ?>" target="_blank"><?php echo $this->translate('global_export_as'); ?>&nbsp;<img src="<?php echo $this->baseUrl('images/excel.png'); ?>" alt="<?php echo $this->translate('global_export_as_excel'); ?>" /></a></div>
  <?php } ?>
  <div id="listresults_div">
    <h2><?php echo $title; ?></h2>
    <table class="list">
      <thead>
        <tr>
          <?php if ($acl->checkPermission('Commodity', ACTION_EDIT) || isLGMISAdmin()) {?>
          <td style="width:5%;">Edit</td>
          <?php } ?>
          <td style="width:40%;"><?php echo $paginate->getSortLinkForColumn('c.name','Commodity'); ?></td>
          <td style="width:30%;"><?php echo $paginate->getSortLinkForColumn('cat.name','Category'); ?></td>
          <td style="width:30%;"><?php echo $paginate->getSortLinkForColumn('u.`name`','Unit'); ?></td>
        </tr>
      </thead>
      <tbody>
        <?php 				  		
            	foreach($result as $line){							
            ?>
        <tr>
          <?php if ($acl->checkPermission('Commodity', ACTION_EDIT) || isLGMISAdmin()) {?>
          <td><a href="<?php echo $this->baseUrl("commodity/index/id/".encode($line['id'])); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>"/></a></td>
          <?php } ?>
          <td class="nowrapping"><a href="<?php echo $this->baseUrl("commodity/view/id/".encode($line['id'])); ?>"><?php echo $line['Commodity']; ?></a></td>
          <td><?php echo $line['Category']; ?></td>
          <td><?php echo $line['Unit']; ?></td>
        </tr>
        <?php 						
            	} // end processing results 
            ?>
      </tbody>
        </tr>
      
    </table>
  </div>
  <?php			
	} // end check that there are results    	
?>
  <div class="paginationlinks"><?php echo $paginate->getPaginationLinks(); ?></div>
</form>
<?php
	$session->setVar(SUCCESS_MESSAGE, "");
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
