<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$subcounty = new Subcounty(); 
	
	// default title is to enable adding any payee
	$title = $this->translate("subcounty_pagetitle_new"); 
	$posturl = $this->baseUrl("subcounty/create");
	$button_title = $this->translate("subcounty_button_new"); 
	
	// set the payee if provided in the url 
	if (!isEmptyString($request->id)) {
		$subcounty->populate(decode($request->id));
		$title = sprintf($this->translate("subcounty_pagetitle_edit"), $subcounty->getName()); 
		$button_title = $this->translate("subcounty_button_edit");
		$posturl = $this->baseUrl("subcounty/edit"); 
	}
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$subcounty->processPost($session->getVar(FORM_VALUES));	
	}
	
	$this->headTitle($title);  
?>
<script>
	$(document).ready(function() {
		$("#subcountyform").validate({		
			// define the validation rules one field at a time
			rules: {
				regionid: "required",
				districtid: "required",
				countyid: "required",
				name: "required"
			}, 
			// the messages for each of the fields being validated
			messages: {				
				regionid: "<?php echo $this->translate("subcounty_region_error"); ?>",
				districtid: "<?php echo $this->translate("subcounty_district_error"); ?>",
				countyid: "<?php echo $this->translate("subcounty_county_error"); ?>",
				name: "<?php echo $this->translate("subcounty_name_error"); ?>"
			}
		});

		// chained select to load the districts for a region
		$('#regionid').selectChain({
		    target: $('#districtid'),
		    url: '<?php echo $this->baseUrl('county/selectchain/'.SELECT_CHAIN_TYPE.'/region_districts/')?>',
		    data: 'currentvalue=<?php echo $subcounty->getDistrictID(); ?>',
		    type: 'get'
		});
		$('#regionid').trigger("change");
		
		// chained select to load the counties for a district
		$('#districtid').selectChain({
		    target: $('#countyid'),
		    url: '<?php echo $this->baseUrl('county/selectchain/'.SELECT_CHAIN_TYPE.'/district_counties/')?>',
		    data: 'currentvalue=<?php echo $subcounty->getCountyID(); ?>',
		    type: 'get'
		});
		$('#districtid').trigger("change");
		
	}); 
</script>

<div class="pageinfo"><?php echo $this->translate("subcounty_page_info"); ?></div>
<form id="subcountyform" action="<?php echo $posturl; ?>" method="post">
  <table class="formtable">
    <tr class="sectionheading">
      <td colspan="2"><?php echo $title; ?></td>
    </tr>
    <?php if ($sessionhaserror) { ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="error"><?php echo $session->getVar(ERROR_MESSAGE); ?></td>
    </tr>
    <?php } ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="pagedescription"><?php echo $this->translate("required_field_info"); ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("subcounty_region_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
      <td><?php
      	$regionlist = new LookupType(); 
      	$regionlist->setName("ALL_REGIONS");
       	$regiondropdown = new Zend_Form_Element_Select('regionid',
							array(
								'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $regionlist->getOptionValuesFromQuery()),								'view' => new Zend_View(),
								'decorators' => array('ViewHelper')
							)
						);
		$regiondropdown->setValue($subcounty->getRegionID()); 
		echo $regiondropdown->render(); 
      ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("subcounty_district_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
      <td><select name="districtid" id="districtid">
          <option value="">&lt;Select One&gt;</option>
        </select></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("subcounty_county_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
      <td><select name="countyid" id="countyid">
          <option value="">&lt;Select One&gt;</option>
        </select></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("subcounty_name_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
      <td><input type="text" name="name" id="name" value="<?php echo $subcounty->getName(); ?>" /></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("subcounty_description_label"); ?>:</td>
      <td><textarea class="expanding" id="description" name="description"><?php echo $subcounty->getDescription(); ?></textarea></td>
    </tr>
  </table>
  <table class="formtable formactions">
    <tfoot>
      <tr>
        <td><a href="<?php echo $this->baseUrl("dataentry"); ?>" title="Cancel">Cancel</a>&nbsp;&nbsp;
          <button type="submit" class="positiveaction" id="submit" name="submit"><img src="<?php echo $this->baseUrl("images/tick.png"); ?>" /><?php echo $button_title; ?></button>
          <input type="hidden" name="entityname" value="Subcounty" />
          <input type="hidden" id="id" name="id" value="<?php echo encode($subcounty->getID()); ?>" /></td>
      </tr>
    </tfoot>
  </table>
</form>
<?php
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
