<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$subcounty = new Subcounty();
	
	// default title is to enable adding any payee
	$title = $this->translate("subcounty_pagetitle_view"); 
	$subcounty->populate(decode($request->id));
	
	$this->headTitle($title);  
?>
<script>
	$(document).ready(function() {		
		$("table.formtable .delete").click(function(){
			if(window.confirm("Are you sure you want to Delete this Sub-County? \n Click OK to confirm or Cancel to stay on this page.")){
				return true;
			} else {
				return false;
			}
		}); 		
	}); 
</script>
<div class="pageinfo"><?php echo $this->translate("subcounty_page_info"); ?></div>
<?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
<div class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
<?php } ?>
<table class="formtable">
  <tr class="sectionheading">
    <td colspan="2"><?php echo $title; ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("subcounty_region_label"); ?>:</td>
    <td><?php echo $subcounty->getRegion()->getName(); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("subcounty_district_label"); ?>:</td>
    <td><?php echo $subcounty->getDistrict()->getName(); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("subcounty_county_label"); ?>:</td>
    <td><?php echo $subcounty->getCounty()->getName(); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("subcounty_name_label"); ?>:</td>
    <td><?php echo $subcounty->getName(); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("subcounty_description_label"); ?>:</td>
    <td><?php echo $subcounty->getDescription(); ?></td>
  </tr> 
</table>
<table class="formtable formactions">
  <tfoot>
    <tr>
      <td><?php if ($acl->checkPermission('Subcounty', ACTION_DELETE) || isLGMISAdmin()) { ?>
        <a href="<?php echo $this->baseUrl('subcounty/delete/entityname/Subcounty/id/'.encode($subcounty->getID()).'/'.SUCCESS_MESSAGE.'/Sub-County has been successfully deleted/'.URL_SUCCESS.'/'.encode($this->baseUrl("subcounty/list"))); ?>" class="negativeaction delete" title="<?php echo $this->translate("subcounty_button_delete"); ?>"><img src="<?php echo $this->baseUrl('images/cross.png'); ?>" /><?php echo $this->translate("subcounty_button_delete"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('Subcounty', ACTION_EDIT) || isLGMISAdmin()) { ?>
        <a href="<?php echo $this->baseUrl('subcounty/index/id/'.encode($subcounty->getID())); ?>" class="positiveaction" title="<?php echo $this->translate("subcounty_pagetitle_edit"); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>" /><?php echo $this->translate("subcounty_pagetitle_edit"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('Subcounty', ACTION_LIST) || isLGMISAdmin()) { ?>
        <a href="<?php echo $this->baseUrl('subcounty/list'); ?>" class="positiveaction" title="<?php echo $this->translate("subcounty_button_list"); ?>"><img src="<?php echo $this->baseUrl('images/arrow_undo.png'); ?>" /><?php echo $this->translate("subcounty_button_list"); ?></a>
        <?php } ?></td>
    </tr>
  </tfoot>
</table>
<?php
	$session->setVar(SUCCESS_MESSAGE, "");
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
