<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$businessdirectorycategory = new BusinessDirectoryCategory();
	
	// default title is to enable adding any payee
	$title = $this->translate("businessdirectorycategory_pagetitle_view"); 
	$businessdirectorycategory->populate(decode($request->id));
		
	$this->headTitle($title);  
?>
<script>
	$(document).ready(function() {		
		$("table.formtable .delete").click(function(){
			if(window.confirm("Are you sure you want to Delete this Business Directory Category? \n Click OK to confirm or Cancel to stay on this page.")){
				return true;
			} else {
				return false;
			}
		}); 		
	}); 
</script>

<div class="pageinfo"><?php echo $this->translate("businessdirectorycategory_page_info"); ?></div>
<?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
<div class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
<?php } ?>
<table class="formtable">
  <tr class="sectionheading">
    <td colspan="2"><?php echo $title; ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("businessdirectorycategory_name_label"); ?>:</td>
    <td><?php echo $businessdirectorycategory->getName(); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("businessdirectorycategory_description_label"); ?>:</td>
    <td><?php echo $businessdirectorycategory->getDescription(); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("businessdirectorycategory_parent_label"); ?>:</td>
    <td><?php echo $businessdirectorycategory->getParent()->getName(); ?></td>
  </tr>
</table>
<br />
<table class="formtable">
  <tfoot>
    <tr>
      <td>	  	
        <?php if ($acl->checkPermission('Business Directory Category', ACTION_DELETE) || isLGMISAdmin()) { ?>
        <a href="<?php echo $this->baseUrl('businessdirectorycategory/delete/entityname/BusinessDirectoryCategory/id/'.encode($businessdirectorycategory->getID()).'/'.SUCCESS_MESSAGE.'/Business Directory Category have been successfully deleted/'.URL_SUCCESS.'/'.encode($this->baseUrl("businessdirectorycategory/list"))); ?>" class="negativeaction delete" title="<?php echo $this->translate("businessdirectorycategory_button_delete"); ?>"><img src="<?php echo $this->baseUrl('images/cross.png'); ?>" /><?php echo $this->translate("businessdirectorycategory_button_delete"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('Business Directory Category', ACTION_EDIT) || isLGMISAdmin()) { ?>
        <a href="<?php echo $this->baseUrl('businessdirectorycategory/index/id/'.encode($businessdirectorycategory->getID())); ?>" class="positiveaction" title="<?php echo $this->translate("businessdirectorycategory_button_edit"); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>" /><?php echo $this->translate("businessdirectorycategory_button_edit"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('Business Directory Category', ACTION_LIST) || isLGMISAdmin()) { ?>
        <a href="<?php echo $this->baseUrl('businessdirectorycategory/list'); ?>" class="positiveaction" title="<?php echo $this->translate("businessdirectorycategory_button_list"); ?>"><img src="<?php echo $this->baseUrl('images/arrow_undo.png'); ?>" /><?php echo $this->translate("businessdirectorycategory_button_list"); ?></a>
        <?php } ?>
      </td>
    </tr>
  </tfoot>
</table>
<?php
	$session->setVar(SUCCESS_MESSAGE, "");
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
