<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$marketanalysisreport = new MarketAnalysisReport();
	
	// default title is to enable adding any payee
	$title = $this->translate("marketanalysisreport_pagetitle_view"); 
	$marketanalysisreport->populate(decode($request->id));
		
	$this->headTitle($title);  
	
?>
<script>
	$(document).ready(function() {		
		$("table.formtable .delete").click(function(){
			if(window.confirm("Are you sure you want to Delete this Market Analysis Report? \n Click OK to confirm or Cancel to stay on this page.")){
				return true;
			} else {
				return false;
			}
		}); 		
	}); 
</script>
<div class="pageinfo"><?php echo $this->translate("marketanalysisreport_page_info"); ?></div>
<?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
<div class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
<?php } ?>
<table class="formtable">
    <tr class="sectionheading">
      <td colspan="2"><?php echo $title; ?></td>
    </tr>
    <?php if ($sessionhaserror) { ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="error"><?php echo $session->getVar(ERROR_MESSAGE); ?></td>
    </tr>
    <?php } ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="pagedescription"><?php echo $this->translate("required_field_info"); ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("marketanalysisreport_reportdate_label"); ?>:</td>
      <td><?php echo changeMySQLDateToPageFormat($marketanalysisreport->getReportDate()); ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("marketanalysisreport_volume_label"); ?>:</td>
      <td><?php echo $marketanalysisreport->getVolume(); ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("marketanalysisreport_number_label"); ?>:</td>
      <td><?php echo $marketanalysisreport->getNumber(); ?></td>
    </tr>
     <tr>
      <td class="label"><?php echo $this->translate("marketanalysisreport_report_label"); ?>:</td>
      <td><?php echo $marketanalysisreport->getLink(); ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("marketanalysisreport_highlights_label"); ?>:</td>
      <td class="nowrapping"><?php echo $marketanalysisreport->getHighlights(); ?></td>
    </tr>    
  </table>
<table class="formtable formactions">
  <tfoot>
    <tr>
      <td><?php if ($acl->checkPermission('Market Analysis Report', ACTION_DELETE)) { ?>
        <a href="<?php echo $this->baseUrl('marketanalysisreport/delete/id/'.encode($marketanalysisreport->getID())); ?>" class="negativeaction delete" title="<?php echo $this->translate("marketanalysisreport_button_delete"); ?>"><img src="<?php echo $this->baseUrl('images/cross.png'); ?>" /><?php echo $this->translate("marketanalysisreport_button_delete"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('Market Analysis Report', ACTION_EDIT)) { ?>
        <a href="<?php echo $this->baseUrl('marketanalysisreport/index/id/'.encode($marketanalysisreport->getID())); ?>" class="positiveaction" title="<?php echo $this->translate("marketanalysisreport_button_edit"); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>" /><?php echo $this->translate("marketanalysisreport_button_edit"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('Market Analysis Report', ACTION_LIST)) { ?>
        <a href="<?php echo $this->baseUrl('marketanalysisreport/list'); ?>" class="positiveaction" title="<?php echo $this->translate("marketanalysisreport_button_list"); ?>"><img src="<?php echo $this->baseUrl('images/arrow_undo.png'); ?>" /><?php echo $this->translate("marketanalysisreport_button_list"); ?></a>
        <?php } ?></td>
    </tr>
  </tfoot>
</table>
<?php
	$session->setVar(SUCCESS_MESSAGE, "");
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
