<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	# Page title
	$title = $this->translate("parish_pagetitle_list");
	$this->headTitle($title);
	
	# Create an instance of the class to handle the pagination
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("p.name","r.name","d.name","c.name","sc.name"));
	$paginate->setDefaultSortBy("p.name");	
	$paginate->setFilterColumns(array("p.regionid","p.districtid","p.countyid","p.subcountyid"));

	$paginate->processPost($request->getParams());
	$all_results_query = "SELECT p.id, p.name AS `Name`, sc.name AS `Sub-County`, c.name AS `County`, d.name as District, r.name as `Region` FROM location p INNER JOIN location r ON p.regionid = r.id INNER JOIN location d ON p.districtid = d.id INNER JOIN location c ON p.countyid = c.id INNER JOIN location sc ON p.subcountyid = sc.id WHERE p.locationtype = 5 ".$paginate->getSearchAndFilterSQL()." ".$paginate->getSortSQL();
	
	# debugMessage($all_results_query);
	$paginate->setItemCountFromSQLQuery($all_results_query);
	
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	//echo $current_results_query;
	$session->setVar(ALL_RESULTS_QUERY, $all_results_query);
	$session->setVar(CURRENT_RESULTS_QUERY, $current_results_query);
	# the query string to be appended to the return to list URL
	$session->setVar('list_query_string'.$request->getControllerName(), $request->getParams());
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
	# This variable stores the number of redundant columns returned in the query so that when we are printing
	# we are able to know how many columns to ignore. This variable is sent in the print URL
	$number_of_redundant_columns = 1;
	
	# the columns which contain numbers in the invoice query
	# Please note that the column count begins at 0
	$export_number_column_list = "";	
?>

<form action="<?php echo $this->baseUrl("parish/listsearch"); ?>" method="get" id="usersform">
  <table class="filtercontainer">
    <tr>
      <td><table class="filtersection">
          <tr>
            <td><?php
				      	$regionlist = new LookupType(); 
				      	$regionlist->setName("ALL_REGIONS");
				       	$regiondropdown = new Zend_Form_Element_Select('p'.HTML_TABLE_COLUMN_SEPARATOR.'regionid',
											array(
												'multiOptions' => array_merge_maintain_keys(array('' => 'All Regions'), $regionlist->getOptionValuesFromQuery()),								'view' => new Zend_View(),
												'decorators' => array('ViewHelper'),
												'class' => array('filterselect', 'chzn-select')
											)
										);
						$regiondropdown->setValue($request->getParam('p'.HTML_TABLE_COLUMN_SEPARATOR.'regionid')); 
						echo $regiondropdown->render(); 
				      ?>
              &nbsp;&nbsp;</td>
            <td><?php
				      	$districtlist = new LookupType(); 
				      	$districtlist->setName("ALL_DISTRICTS");
				       	$districtdropdown = new Zend_Form_Element_Select('p'.HTML_TABLE_COLUMN_SEPARATOR.'districtid',
											array(
												'multiOptions' => array_merge_maintain_keys(array('' => 'All Districts'), $districtlist->getOptionValuesFromQuery()),								'view' => new Zend_View(),
												'decorators' => array('ViewHelper'),
												'class' => array('filterselect', 'chzn-select')
											)
										);
						$districtdropdown->setValue($request->getParam('p'.HTML_TABLE_COLUMN_SEPARATOR.'districtid')); 
						echo $districtdropdown->render(); 
				      ?>
              &nbsp;&nbsp;</td>
            <td><?php
				      	$countylist = new LookupType(); 
				      	$countylist->setName("ALL_COUNTIES");
				       	$countydropdown = new Zend_Form_Element_Select('p'.HTML_TABLE_COLUMN_SEPARATOR.'countyid',
											array(
												'multiOptions' => array_merge_maintain_keys(array('' => 'All Counties'), $countylist->getOptionValuesFromQuery()),								'view' => new Zend_View(),
												'decorators' => array('ViewHelper'),
												'class' => array('filterselect', 'chzn-select')
											)
										);
						$countydropdown->setValue($request->getParam('p'.HTML_TABLE_COLUMN_SEPARATOR.'countyid')); 
						echo $countydropdown->render(); 
				      ?></td>
          </tr>
        </table></td>
      <td><table>
          <tr>
            <td><input class="filterselect" type="text" name="searchterm" id="searchterm" value="<?php echo $request->searchterm; ?>" title="Enter your search term here and click search" /></td>
          </tr>
          <tr>
            <td><button type="submit" class="positiveaction" id="searchbutton" title="Click here to Search or Filter"><img src="<?php echo $this->baseUrl("images/zoom_in.png"); ?>" alt="Search"/>Search</button></td>
          </tr>
        </table></td>
    </tr>
  </table>
  <?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
  <div class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
  <?php } ?>
  <?php // show a message that there are no items to display
	if ($has_no_data) {
?>
  <label class="error"><?php echo $this->translate("parish_list_norecords"); ?></label>
  <?php } else { ?>
  <div id="counter"><?php echo sprintf($this->translate("parish_list_counter"), $paginate->getItemCounterText()); ?></div>
  <div id="listcounter"><?php echo $this->listcountdropdown; ?></div>
  <div id="print"><a title="<?php echo $this->translate('global_print_as'); ?>" href="<?php echo $this->baseUrl('index/printerfriendly/'.EXPORT_NUMBER_COLUMN_LIST.'/'.$export_number_column_list.'/'.EXPORT_IGNORE_COLUMN_COUNT.'/'.$number_of_redundant_columns.'/'.PAGE_TITLE.'/'.$title); ?>" target="_blank"><?php echo $this->translate('global_print'); ?>&nbsp;<img src="<?php echo $this->baseUrl('images/printer.png'); ?>" alt="<?php echo $this->translate('global_print_as'); ?>" /></a></div>  
  <?php if ($acl->checkPermission('Parish', ACTION_EXPORT)) { ?>
  <div id="export"><a title="<?php echo $this->translate('global_export_as_excel'); ?>" href="<?php echo $this->baseUrl('index/exceldownload/'.EXPORT_NUMBER_COLUMN_LIST.'/'.$export_number_column_list.'/'.EXPORT_IGNORE_COLUMN_COUNT.'/'.$number_of_redundant_columns); ?>" target="_blank"><?php echo $this->translate('global_export_as'); ?>&nbsp;<img src="<?php echo $this->baseUrl('images/excel.png'); ?>" alt="<?php echo $this->translate('global_export_as_excel'); ?>" /></a></div>
  <?php } ?>
  <div id="listresults_div">
    <h2><?php echo $title; ?></h2>
    <table class="list">
      <thead>
        <tr>
          <?php if ($acl->checkPermission('Parish', ACTION_EDIT)) {?>
          <td>Edit</td>
          <?php } ?>
          <td><?php echo $paginate->getSortLinkForColumn('p.name','Name'); ?></td>
          <td><?php echo $paginate->getSortLinkForColumn('sc.name','Sub-County'); ?></td>
          <td><?php echo $paginate->getSortLinkForColumn('c.name','County'); ?></td>
          <td><?php echo $paginate->getSortLinkForColumn('d.name','District'); ?></td>
          <td><?php echo $paginate->getSortLinkForColumn('r.name','Region'); ?></td>
        </tr>
      </thead>
      <tbody>
        <?php 				  		
            	foreach($result as $line){							
            ?>
        <tr>
          <?php if ($acl->checkPermission('Subcounty', ACTION_EDIT)) {?>
          <td class="nowrapping"><a href="<?php echo $this->baseUrl("parish/index/id/".encode($line['id'])); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>"/></a></td>
          <?php } ?>
          <td class="nowrapping"><a href="<?php echo $this->baseUrl("parish/view/id/".encode($line['id'])); ?>"><?php echo $line['Name']; ?></a></td>
          <td class="nowrapping"><?php echo $line['Sub-County']; ?></td>
          <td class="nowrapping"><?php echo $line['County']; ?></td>
          <td class="nowrapping"><?php echo $line['District']; ?></td>
          <td class="nowrapping"><?php echo $line['Region']; ?></td>
        </tr>
        <?php 						
            	} // end processing results 
            ?>
      </tbody>
        </tr>
      
    </table>
  </div>
  <?php			
	} // end check that there are results    	
?>
  <div class="paginationlinks"><?php echo $paginate->getPaginationLinks(); ?></div>
</form>
<?php
	$session->setVar(SUCCESS_MESSAGE, "");
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
