<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$pricecategory = new PriceCategory(); 
	
	// default title is to enable adding any payee
	$title = $this->translate("pricecategory_pagetitle_new"); 
	$posturl = $this->baseUrl("pricecategory/create");
	$button_title = $this->translate("pricecategory_button_new"); 
	
	// set the payee if provided in the url 
	if (!isEmptyString($request->id)) {
		$pricecategory->populate(decode($request->id));
		$title = sprintf($this->translate("pricecategory_pagetitle_edit"), $pricecategory->getName()); 
		$button_title = $this->translate("pricecategory_button_edit");
		$posturl = $this->baseUrl("pricecategory/edit"); 
	}
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$pricecategory->processPost($session->getVar(FORM_VALUES));	
	}
	
	$this->headTitle($title);  
?>
<script>
	$(document).ready(function() {
		$("#pricecategoryform").validate({		
			// define the validation rules one field at a time
			rules: {
				name: "required"
			}, 
			// the messages for each of the fields being validated
			messages: {				
				name: "<?php echo $this->translate("pricecategory_name_error"); ?>"
			}
		});
	}); 
</script>

<div class="pageinfo"><?php echo $this->translate("pricecategory_page_info"); ?></div>
<form id="pricecategoryform" action="<?php echo $posturl; ?>" method="post">
  <table class="formtable">
    <tr class="sectionheading">
      <td colspan="2"><?php echo $title; ?></td>
    </tr>
    <?php if ($sessionhaserror) { ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="error"><?php echo $session->getVar(ERROR_MESSAGE); ?></td>
    </tr>
    <?php } ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="pagedescription"><?php echo $this->translate("required_field_info"); ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("pricecategory_name_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
      <td><input type="text" name="name" id="name" value="<?php echo $pricecategory->getName(); ?>" /></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("pricecategory_description_label"); ?>:</td>
      <td><textarea class="expanding" id="description" name="description"><?php echo $pricecategory->getDescription(); ?></textarea></td>
    </tr>    
  </table>
  <table class="formtable formactions">
    <tfoot>
      <tr>
        <td><a href="<?php echo $this->baseUrl("pricecategory/list"); ?>" title="Cancel">Cancel</a>&nbsp;&nbsp;
          <button type="submit" class="positiveaction" id="submit" name="submit"><img src="<?php echo $this->baseUrl("images/tick.png"); ?>" /><?php echo $button_title; ?></button>
          <input type="hidden" name="entityname" value="PriceCategory" />
          <input type="hidden" id="id" name="id" value="<?php echo encode($pricecategory->getID()); ?>" /></td>
      </tr>
    </tfoot>
  </table>
</form>
<?php
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
