<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$pricecategory = new PriceCategory();
	
	// default title is to enable adding any payee
	$title = $this->translate("pricecategory_pagetitle_view"); 
	$pricecategory->populate(decode($request->id));
		
	$this->headTitle($title);  
?>
<script>
	$(document).ready(function() {		
		$("table.formtable .delete").click(function(){
			if(window.confirm("Are you sure you want to Delete this Price Category? \n Click OK to confirm or Cancel to stay on this page.")){
				return true;
			} else {
				return false;
			}
		}); 		
	}); 
</script>

<div class="pageinfo"><?php echo $this->translate("pricecategory_page_info"); ?></div>
<?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
<div class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
<?php } ?>
<table class="formtable">
  <tr class="sectionheading">
    <td colspan="2"><?php echo $title; ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("pricecategory_name_label"); ?>:</td>
    <td><?php echo $pricecategory->getName(); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("pricecategory_description_label"); ?>:</td>
    <td><?php echo $pricecategory->getDescription(); ?></td>
  </tr>
</table>
<table class="formtable formactions">
  <tfoot>
    <tr>
      <td><?php if ($acl->checkPermission('Price Category', ACTION_DELETE)) { ?>
        <a href="<?php echo $this->baseUrl('pricecategory/delete/entityname/PriceCategory/id/'.encode($pricecategory->getID()).'/'.SUCCESS_MESSAGE.'/Price Category has been successfully deleted/'.URL_SUCCESS.'/'.encode($this->baseUrl("pricecategory/list"))); ?>" class="negativeaction delete" title="<?php echo $this->translate("pricecategory_button_delete"); ?>"><img src="<?php echo $this->baseUrl('images/cross.png'); ?>" /><?php echo $this->translate("pricecategory_button_delete"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('Price Category', ACTION_EDIT)) { ?>
        <a href="<?php echo $this->baseUrl('pricecategory/index/id/'.encode($pricecategory->getID())); ?>" class="positiveaction" title="<?php echo $this->translate("pricecategory_button_edit"); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>" /><?php echo $this->translate("pricecategory_button_edit"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('Price Category', ACTION_LIST)) { ?>
        <a href="<?php echo $this->baseUrl('pricecategory/list'); ?>" class="positiveaction" title="<?php echo $this->translate("pricecategory_button_list"); ?>"><img src="<?php echo $this->baseUrl('images/arrow_undo.png'); ?>" /><?php echo $this->translate("pricecategory_button_list"); ?></a>
        <?php } ?></td>
    </tr>
  </tfoot>
</table>
<?php
	$session->setVar(SUCCESS_MESSAGE, "");
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
