<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$locationstatistic = new LocationStatistic(); 
	
	// default title is to enable adding any payee
	$title = $this->translate("locationstatistic_pagetitle_new"); 
	$posturl = $this->baseUrl("locationstatistic/create");
	$button_title = $this->translate("locationstatistic_button_new"); 
	
	// set the payee if provided in the url 
	if (!isEmptyString($request->id)) {
		$locationstatistic->populate(decode($request->id));
		$title = sprintf($this->translate("locationstatistic_pagetitle_edit"), $locationstatistic->getLocation()->getName()); 
		$button_title = $this->translate("global_button_save_changes");
		$posturl = $this->baseUrl("locationstatistic/edit"); 
	}
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$locationstatistic->processPost($session->getVar(FORM_VALUES));	
	}
	
	$this->headTitle($title);  
?>
<script>
	$(document).ready(function() {
		// configure the date picker not to accept dates before today
		// datepickerOpts.minDate = new Date();   
		 
		datepickerOpts.minDate = new Date();   
		$("#startdate, #enddate").datepicker(datepickerOpts);
	
		$("#locationstatisticform").validate({		
			// define the validation rules one field at a time
			rules: {
				locationid: "required",
				startdate: "required",
				enddate: {
					required: true,
					enddateafterstartdate: true
				},
				statisticid: "required",
				unitid: "required",
				value: "required"
			}, 
			// the messages for each of the fields being validated
			messages: {				
				locationid: "<?php echo $this->translate("locationstatistic_location_error"); ?>",
				startdate: "<?php echo $this->translate("locationstatistic_startdate_error"); ?>",
				enddate: {
					required: "<?php echo $this->translate("locationstatistic_enddate_error"); ?>"						
				},
				statisticid: "<?php echo $this->translate("locationstatistic_statistic_error"); ?>",
				unitid: "<?php echo $this->translate("locationstatistic_measure_error"); ?>",
				value: "<?php echo $this->translate("locationstatistic_statistic_value_error"); ?>"
			},
			// custom error positions
			errorPlacement: function(error, element) {
				switch(element.attr("name")){					
					case 'locationid':
						error.appendTo("#locationid_error");
						break;	
					case 'statisticid':
						error.appendTo("#statisticid_error");
						break;	
					case 'startdate':
						error.appendTo("#startdate_error");
						break;	
					case 'enddate':
						error.appendTo("#enddate_error");
						break;
					case 'unitid':
						error.appendTo("#unitid_error");
						break;
					default:
						error.insertAfter(element);
						break;
				}
			}		
		});

	});
</script>
<style>
table.formtable tr td, table.formtable tr td.label {
	vertical-align:middle;
}
input.smallnumberfield {
	width:150px;
}
select.chzn-select.parameter {
	min-width:215px;
}
select.chzn-select.unit {
	min-width:150px;
}
</style>
<div class="pageinfo"><?php echo $this->translate("locationstatistic_page_info"); ?></div>
<form id="locationstatisticform" action="<?php echo $posturl; ?>" method="post">
  <table class="formtable">
    <tr class="sectionheading">
      <td colspan="2"><?php echo $title; ?></td>
    </tr>
    <?php if ($sessionhaserror) { ?>
    <tr>
      <td class="error" colspan="2"><?php echo $session->getVar(ERROR_MESSAGE); ?></td>
    </tr>
    <?php } ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="pagedescription"><?php echo $this->translate("required_field_info"); ?></td>
    </tr>
   <?php if(isLGMISAdmin()) { ?>
    <tr>
      <td class="label"><?php echo $this->translate("locationstatistic_locationid_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
      <td>
	  	<?php
			$districtlist = new LookupType(); 
			$districtlist->setName("ALL_DISTRICTS");
			$districtdropdown = new Zend_Form_Element_Select('locationid',
								array(
									'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $districtlist->getOptionValuesFromQuery()),								
									'view' => new Zend_View(),
									'decorators' => array('ViewHelper'),
									'class' => array("filterselect", 'chzn-select'),
								)
							);
			$districtdropdown->setValue($locationstatistic->getLocationID()); 
			echo $districtdropdown->render(); 
		  ?><div id="locationid_error"></div>
          </td>
    </tr>
    <?php } else { ?>
	    <input type="hidden" id="locationid" name="locationid" value="<?php echo $locationstatistic->getLocationID(); ?>" />
    <?php } ?>
    <tr>
      <td class="label"><?php echo $this->translate("locationstatistic_startdate_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
     <td>
     	<?php if(isLGMISAdmin()) { ?>
        	<input name="startdate" id="startdate" class="datefield startdate" type="text" value="<?php echo changemySQlDatetoPageFormat($locationstatistic->getStartDate()); ?>" />
        <?php } else { ?>
	    	<input type="hidden" id="startdate" name="startdate" class="startdate" value="<?php echo $locationstatistic->getStartDate(); ?>" />
			<?php echo changemySQlDatetoPageFormat($locationstatistic->getStartDate()); ?>
    	<?php } ?><div id="startdate_error"></div>
        </td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("locationstatistic_enddate_label"); ?>: <?php echo $this->translate("required_field_marker"); ?></td>
      <td>
     	<?php if(isLGMISAdmin()) { ?>
     		<input name="enddate" id="enddate" class="datefield" type="text" value="<?php echo changemySQlDatetoPageFormat($locationstatistic->getEndDate()); ?>" /></td>
     	<?php } else { ?>
            <input type="hidden" id="enddate" name="enddate" value="<?php echo $locationstatistic->getEndDate(); ?>" />
            <?php echo changemySQlDatetoPageFormat($locationstatistic->getEndDate()); ?>
    	<?php } ?><div id="enddate_error"></div>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("locationstatistic_statistic_label"); ?>: <?php echo $this->translate("required_field_marker"); ?></td>
       <td><?php
				$statisticvalues = getAllStatisticValues(); 
				$statisticvalues = array_merge_maintain_keys(array('' => 'Select Parameter'), $statisticvalues);
				
				$unitvalues = getAllStatisticUnits(); 
				$unitvalues = array_merge_maintain_keys(array('' => 'Select Measure'), $unitvalues);
                $statisticropdown = new Zend_Form_Element_Select('statisticid',
                                    array(
                                        'multiOptions' => $statisticvalues,								
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper'),
                                        'class' => array("filterselect", 'chzn-select', 'parameter'),
                                    )
                                );
                $statisticropdown->setValue($locationstatistic->getStatisticID()); 
                echo $statisticropdown->render(); 
              ?><div id="statisticid_error"></div>
            </td>
    </tr>
    <tr>
    	<td class="label"><?php echo $this->translate("locationstatistic_measure_label"); ?>: <?php echo $this->translate("required_field_marker"); ?></td>
    	<td><?php
                $unitdropdown = new Zend_Form_Element_Select('unitid',
                                    array(
                                        'multiOptions' => $unitvalues,								
                                        'view' => new Zend_View(),
                                        'decorators' => array('ViewHelper'),
                                        'class' => array("filterselect", 'chzn-select', 'unit'),
                                    )
                                );
                $unitdropdown->setValue($locationstatistic->getUnitID()); 
                echo $unitdropdown->render(); 
              ?><div id="unitid_error"></div></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("locationstatistic_value_label"); ?>: <?php echo $this->translate("required_field_marker"); ?></td>
      <td><input type="text" name="value" id="value" class="smallnumberfield" value="<?php echo clean_num($locationstatistic->getValue()); ?>" /></td>
    </tr>	
  </table>
  <table class="formtable formactions">
    <tfoot>
      <tr>
        <td><a href="<?php echo $this->baseUrl("dataentry"); ?>" title="Cancel">Cancel</a>&nbsp;&nbsp;
          <button type="submit" class="positiveaction" id="submit" name="submit"><img src="<?php echo $this->baseUrl("images/tick.png"); ?>" /><?php echo $button_title; ?></button>
          <input type="hidden" name="entityname" value="LocationStatistic" />
          <input type="hidden" id="id" name="id" value="<?php echo encode($locationstatistic->getID()); ?>" /></td>
      </tr>
    </tfoot>
  </table>
</form>
<?php
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
