<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$locationstatistic = new LocationStatistic();
	
	// default title is to enable adding any payee
	$title = $this->translate("locationstatistic_pagetitle_view"); 
	$locationstatistic->populate(decode($request->id));
	
	$this->headTitle($title);  
?>
<script>
	$(document).ready(function() {		
		$("table.formtable .delete").click(function(){
			if(window.confirm("Are you sure you want to Delete this Location Statistic? \n Click OK to confirm or Cancel to stay on this page.")){
				return true;
			} else {
				return false;
			}
		}); 		
	}); 
</script>
<div class="pageinfo"><?php echo $this->translate("locationstatistic_page_info"); ?></div>
<?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
<div class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
<?php } ?>
<table class="formtable">
    <tr class="sectionheading">
    	<td colspan="2"><?php echo $title; ?></td>
    </tr>
    <tr>
        <td class="label"><?php echo $this->translate("locationstatistic_locationid_label"); ?>:</td>
        <td><?php echo $locationstatistic->getLocation()->getName(); ?></td>
    </tr>
    <tr>
        <td class="label"><?php echo $this->translate("locationstatistic_startdate_label"); ?>:</td>
        <td><?php echo changemySQlDatetoPageFormat($locationstatistic->getStartdate()); ?></td>
    </tr>
    <tr>
        <td class="label"><?php echo $this->translate("locationstatistic_enddate_label"); ?>:</td>
        <td><?php echo changemySQlDatetoPageFormat($locationstatistic->getEnddate()); ?></td>
    </tr>
    <tr>
        <td class="label"><?php echo $this->translate("locationstatistic_statistic_label"); ?>:</td>
        <td><?php echo $locationstatistic->getStatistic()->getValue(); ?></td>
    </tr>
    <tr>
        <td class="label"><?php echo $this->translate("locationstatistic_measure_label"); ?>:</td>
        <td><?php echo $locationstatistic->getUnit()->getName(); ?></td>
    </tr>
    <tr>
        <td class="label"><?php echo $this->translate("locationstatistic_value_label"); ?>:</td>
        <td><?php echo clean_num($locationstatistic->getValue()); ?></td>
    </tr>
</table>
<table class="formtable formactions">
  <tfoot>
    <tr>
      <td><?php if ($acl->checkPermission('Location Statistic', ACTION_DELETE)) { ?>
        <a href="<?php echo $this->baseUrl('locationstatistic/delete/entityname/LocationStatistic/id/'.encode($locationstatistic->getID()).'/'.SUCCESS_MESSAGE.'/Location Statistic has been successfully deleted/'.URL_SUCCESS.'/'.encode($this->baseUrl("locationstatistic/list"))); ?>" class="negativeaction delete" title="<?php echo $this->translate("locationstatistic_button_delete"); ?>"><img src="<?php echo $this->baseUrl('images/cross.png'); ?>" /><?php echo $this->translate("global_button_delete"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('Location Statistic', ACTION_EDIT)) { ?>
        <a href="<?php echo $this->baseUrl('locationstatistic/index/id/'.encode($locationstatistic->getID())); ?>" class="positiveaction" title="<?php echo $this->translate("locationstatistic_pagetitle_edit"); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>" /><?php echo $this->translate("global_button_update"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('Location Statistic', ACTION_LIST)) { ?>
        <a href="<?php echo $this->baseUrl('locationstatistic/list'); ?>" class="positiveaction" title="<?php echo $this->translate("locationstatistic_button_list"); ?>"><img src="<?php echo $this->baseUrl('images/arrow_undo.png'); ?>" /><?php echo $this->translate("locationstatistic_button_list"); ?></a>
        <?php } ?></td>
    </tr>
  </tfoot>
</table>
<?php
	$session->setVar(SUCCESS_MESSAGE, "");
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
