<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$pricesubmission = new CommodityPriceSubmission();
	$hasprices = true;
	if($pricesubmission->getLatestPriceSubmissionIDForLocation($request->id) === false){
		$hasprices = false;
	}
    
	$location = new District();
	$location->populate($request->id);	
	// default title is to enable adding any payee
	$title = $location->getName()." Agricultural Inputs";
	$place = $location->getName();
	$this->headTitle($title);	
	
?>
<style>
#rightcolumn {
	display:none;
}
#contentwrapper {
	width: 950px;
	border:solid 1px #CCCCCC;
	border-top:none;
	background-color:#FFFFFF;
	background-image:none;
}
#contentleft {
	min-height:150px;
	height:auto;
}
#contentright {
	min-height:150px;
	height:auto;
}
</style>
<div id="lgmiswrapper">
<?php require_once APPLICATION_PATH.'/views/scripts/lgmis/menu.phtml'; ?>
	<div id="contentleft" class="globalfont">
    	<h1 class="pagetitle"><?php echo $title; ?></h1>
       	<div class="widgetsection height100">
            <h3><?php echo $this->translate('lgmis_sector_overview'); ?></h3>
            <label><?php echo isEmptyString($location->getLocationDetail()->getAgriculturalInputPrices()) ? 'No information currently available for '.$place : nl2br($location->getLocationDetail()->getAgriculturalInputPrices()); ?></label>
        </div> 
    </div>
    <!--<div id="contentright" class="globalfont">
    	<div class="widgetsection height150">
        	<h3>TBD</h3>
        </div>
   	</div>-->
	<div class="widgetsection height300 globalfont" style="display:block; clear:both;">
        <h3><?php echo $this->translate('lgmis_sector_information'); ?></h3>
        <?php 
            # Fetch Existing Price Details for the current submission
            $commodities = $pricesubmission->getCurrentPriceDetails(6);
            // debugMessage($result);
            $i = 0;
            
        ?>    	 
        <?php if(!$hasprices){ ?>
            <label class="informationmessage">No information currently available for <?php echo $place; ?></label>
        <?php } else { ?>
            <label class="subtitle">Prices in <b><?php echo $place; ?></b> as at <b><?php echo changeMySQLDateToPageFormat($pricesubmission->getDateCollected()); ?></b></label>
            <table class="formtable commodities">
                <thead>
                  <tr class="sectionheading">
                    <td align="left" class="nowrapping"><?php echo $this->translate("commodityprice_commodity_label"); ?></td>
                    <td align="center" width="60">Unit<?php //echo $this->translate("commodityprice_units_label"); ?></td>
                    <td align="center" width="140">Wholesale (Shs)<?php //echo $this->translate("commodityprice_wholesale_label"); ?></td>
                    <td align="center" width="115">Retail (Shs)<?php //echo $this->translate("commodityprice_retail_label"); ?></td>        
                    <td align="center" width="40">Notes</td>
                  </tr>
                </thead>
                <?php   
                    foreach($commodities as $commodity){
                ?>
                <tr class="<?php echo $commodity['categoryid']; ?>">
                  <td align="left"><?php echo $commodity['name']; ?></td>
                  <td align="center"><?php echo $commodity['units']; ?></td>
                  <td align="center" class="prices"><?php echo formatNumber($commodity['wholesaleprice']); ?></td>
                  <td align="center" class="prices"><?php echo formatNumber($commodity['retailprice']); ?></td>
                  <td align="center"><script>
                        $(document).ready(function(){				
                            
                            $("#notes_<?php echo $i; ?>_trigger").click(function(){					
                                $("#dialog_<?php echo $i; ?>").dialog({
                                    width: 500,
                                    height: 200,
                                    show: 'slide',						
                                    modal: true,
                                    title: $(this).attr('title'),						
                                    buttons: [{text: "Ok", click: function() { $(this).dialog("close"); }}] 
                                });
                            });
                        });
                    </script>
                    <?php if(isEmptyString($commodity['notes'])){ ?>
                    ---
                    <?php } else { ?>
                    <a href="javascript: doNothing();" class="notes" id="notes_<?php echo $i; ?>_trigger" title="Notes for <?php echo $commodity['name']; ?>"><img src="<?php echo $this->baseUrl('images/notes_plus.png'); ?>" /></a>
                    <div id="dialog_<?php echo $i; ?>" class="hidden" style="width:500px; height:250px;">
                      <label><?php echo nl2br($commodity['notes']); ?></label>
                    </div>
                    <?php } ?></td>
                </tr>
                <?php $i++;
                 }	
                ?>
              </table>
        <?php } ?>
    </div>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
