<style>
#rightcolumn, table.formactions {
	display:none;
}
#contentwrapper {
	width: 950px;
	border:solid 1px #CCCCCC;
	border-top:none;
	background-color:#FFFFFF;
	background-image:none;
}
table.formtable {
	width: 100%; 
} 

</style>
<div id="lgmis">
<?php require_once APPLICATION_PATH.'/views/scripts/lgmis/menu.phtml'; ?>
<?php
	require_once APPLICATION_PATH.'/views/scripts/touristattraction/view.phtml';
?>
</div>