<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$commoditycategory = new CommodityCategory();
	
	// default title is to enable adding any payee
	$title = $this->translate("commoditycategory_pagetitle_view"); 
	$commoditycategory->populate(decode($request->id));
		
	$this->headTitle($title);  
?>
<script>
	$(document).ready(function() {		
		$("table.formtable .delete").click(function(){
			if(window.confirm("Are you sure you want to Delete this Commodity Category? \n Click OK to confirm or Cancel to stay on this page.")){
				return true;
			} else {
				return false;
			}
		}); 		
	}); 
</script>

<div class="pageinfo"><?php echo $this->translate("commoditycategory_page_info"); ?></div>
<?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
<div class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
<?php } ?>
<table class="formtable">
  <tr class="sectionheading">
    <td colspan="2"><?php echo $title; ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("commoditycategory_name_label"); ?>:</td>
    <td><?php echo $commoditycategory->getName(); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("commoditycategory_parent_label"); ?>:</td>
    <td><?php echo $commoditycategory->getParent()->getName(); ?></td>
  </tr>  
  <tr>
    <td class="label"><?php echo $this->translate("commoditycategory_description_label"); ?>:</td>
    <td><?php echo $commoditycategory->getDescription(); ?></td>
  </tr>
</table>
<table class="formtable formactions">
  <tfoot>
    <tr>
      <td><?php if ($acl->checkPermission('Commodity Category', ACTION_DELETE) || isLGMISAdmin()) { ?>
        <a href="<?php echo $this->baseUrl('commoditycategory/delete/entityname/CommodityCategory/id/'.encode($commoditycategory->getID()).'/'.SUCCESS_MESSAGE.'/Commodity Category have been successfully deleted/'.URL_SUCCESS.'/'.encode($this->baseUrl("commoditycategory/list"))); ?>" class="negativeaction delete" title="<?php echo $this->translate("commoditycategory_button_delete"); ?>"><img src="<?php echo $this->baseUrl('images/cross.png'); ?>" /><?php echo $this->translate("commoditycategory_button_delete"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('Commodity Category', ACTION_EDIT) || isLGMISAdmin()) { ?>
        <a href="<?php echo $this->baseUrl('commoditycategory/index/id/'.encode($commoditycategory->getID())); ?>" class="positiveaction" title="<?php echo $this->translate("commoditycategory_button_edit"); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>" /><?php echo $this->translate("commoditycategory_button_edit"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('Commodity Category', ACTION_LIST) || isLGMISAdmin()) { ?>
        <a href="<?php echo $this->baseUrl('commoditycategory/list'); ?>" class="positiveaction" title="<?php echo $this->translate("commoditycategory_button_list"); ?>"><img src="<?php echo $this->baseUrl('images/arrow_undo.png'); ?>" /><?php echo $this->translate("commoditycategory_button_list"); ?></a>
        <?php } ?></td>
    </tr>
  </tfoot>
</table>
<?php
	$session->setVar(SUCCESS_MESSAGE, "");
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
