<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$pricesource = new PriceSource();
	
	// default title is to enable adding any payee
	$title = $this->translate("pricesource_pagetitle_view"); 
	$pricesource->populate(decode($request->id));
	
	$this->headTitle($title);  
?>
<script>
	$(document).ready(function() {		
		$("table.formtable .delete").click(function(){
			if(window.confirm("Are you sure you want to Delete this Price Source? \n Click OK to confirm or Cancel to stay on this page.")){
				return true;
			} else {
				return false;
			}
		}); 		
	}); 
</script>

<div class="pageinfo"><?php echo $this->translate("pricesource_page_info"); ?></div>
<?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
<div class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
<?php } ?>
<table class="formtable">
  <tr class="sectionheading">
    <td colspan="2"><?php echo $title; ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("pricesource_name_label"); ?>:</td>
    <td><?php echo $pricesource->getName(); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("pricesource_pricecategoryid_label"); ?>:</td>
    <td><?php echo $pricesource->displayCategories(); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("pricesource_phone_label"); ?>:</td>
    <td><?php echo $pricesource->getPhone(); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("pricesource_email_label"); ?>:</td>
    <td><?php echo $pricesource->getEmail(); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("pricesource_contactperson_label"); ?>:</td>
    <td><?php echo $pricesource->getContactPerson(); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("pricesource_location_label"); ?>:</td>
    <td><?php echo $pricesource->getLocation()->getName(); ?></td>
  </tr>
  <tr>
      <td class="label"><?php echo $this->translate("useraccount_applicationtype_label"); ?>:</td>
      <td><?php echo $pricesource->getApplicationTypeDescription(); ?></td>
	</tr>
  <tr>
    <td class="label"><?php echo $this->translate("pricesource_address_label"); ?>:</td>
    <td><?php echo nl2br($pricesource->getAddress()); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("pricesource_notes_label"); ?>:</td>
    <td><?php echo nl2br($pricesource->getNotes()); ?></td>
  </tr>
</table>
<table class="formtable formactions">
  <tfoot>
    <tr>
      <td><?php if ($acl->checkPermission('Price Source', ACTION_DELETE)) { ?>
        <a href="<?php echo $this->baseUrl('pricesource/delete/entityname/PriceSource/id/'.encode($pricesource->getID()).'/'.SUCCESS_MESSAGE.'/Price Source has been successfully deleted/'.URL_SUCCESS.'/'.encode($this->baseUrl("pricesource/list"))); ?>" class="negativeaction delete" title="<?php echo $this->translate("pricesource_button_delete"); ?>"><img src="<?php echo $this->baseUrl('images/cross.png'); ?>" /><?php echo $this->translate("pricesource_button_delete"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('Price Source', ACTION_EDIT)) { ?>
        <a href="<?php echo $this->baseUrl('pricesource/index/id/'.encode($pricesource->getID())); ?>" class="positiveaction" title="<?php echo $this->translate("pricesource_pagetitle_edit"); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>" /><?php echo $this->translate("pricesource_button_edit"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('Price Source', ACTION_LIST)) { ?>
        <a href="<?php echo $this->baseUrl('pricesource/list'); ?>" class="positiveaction" title="<?php echo $this->translate("pricesource_button_list"); ?>"><img src="<?php echo $this->baseUrl('images/arrow_undo.png'); ?>" /><?php echo $this->translate("pricesource_button_list"); ?></a>
        <?php } ?></td>
    </tr>
  </tfoot>
</table>
<?php
	$session->setVar(SUCCESS_MESSAGE, "");
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
