<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$pricesubmission = new CommodityPriceSubmission();
	
	$posturl = $this->baseUrl("inputproduction/create");
	$title = $this->translate("commodityprice_input_pagetitle_new"); 
	$button_title_save = $this->translate("commodityprice_save_button_new"); 
	$button_title_submit = $this->translate("commodityprice_submit_button_new"); 
	
	# determine logged in user
	if (isLGMISAdmin()) { 
		$can_view_all = true;
	} else {
		$can_view_all = false;
		if(!isEmptyString($session->getVar("districtid"))){
			$title = "New ".$session->getVar("districtname")." District Input Prices";
			$pricesubmission->setSourceID($session->getVar("districtpricesourceid"));
			// debugMessage($session->getVar("districtpricesourceid"));
		}
	}
		
	// set the payee if provided in the url 
	if (!isEmptyString($request->id)) {
		$pricesubmission->populate(decode($request->id));
		$posturl = $this->baseUrl("inputproduction/edit"); 
		$button_title_save = $this->translate("global_button_save_changes"); 
		$title = $this->translate("commodityprice_input_pagetitle_edit"); 		
		if (!isLGMISAdmin()) { 
			$title = "Update ".$pricesubmission->getSource()->getLocation()->getName()." District Input Prices";
		}
	} else {
		# set default value of submitted by to the loggedin user
		$pricesubmission->setCollectedByID($userid);
		# set default collection date to todays date
		$pricesubmission->setDateCollected(date($config->dateandtime->mediumformat));	
	}
	
	# Fetch Existing Price Details for the current submission
	$commodities = array();
	$commodities = $pricesubmission->getCurrentPriceDetails(6);	
	#in case of errors in session, populate the fields from session
	
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$formvalues = $session->getVar(FORM_VALUES);		
		$pricesubmission->processPost($formvalues);
	}
	
	$this->headTitle($title);  
?>
<script>
	$(document).ready(function() {
		
		datepickerOpts.maxDate = new Date();   
		$("#datecollected").datepicker(datepickerOpts); 
		
		$.validator.addMethod("wholesalelessthanretail", 
			function(value, element, params) { 
				var wholesalepricefield = element.id; 
				var retailpricefield = wholesalepricefield.replace('wholesale', 'retail');
				// check whether the retail price has a value, if not do not validate 
				if ($("#" + retailpricefield).val() == "") {
					return true; 
				} else {
					// check whether the wholesale price is greater than the retail price
					if(parseFloat($("#" + wholesalepricefield).val()) > parseFloat($("#" + retailpricefield).val())) {
						return false; 
					} else {
						return true; 
					} 
				}
				return false;        
			}, "<?php echo $this->translate("commodityprice_wholesaleprice_invalid_error"); ?>");
		
		$("#priceform").validate({		
			// define the validation rules one field at a time
			rules: {
				datecollected: "required",
				collectedbyid: "required",
				sourceid: "required",
				comments: "required"
			}, 
			// the messages for each of the fields being validated
			messages: {				
				datecollected: "<?php echo $this->translate("commodityprice_datecollected_error"); ?>",
				collectedbyid: "<?php echo $this->translate("commodityprice_collectedby_error"); ?>",
				sourceid: "<?php echo $this->translate("commodityprice_source_error"); ?>",
				comments: "<?php echo $this->translate("commodityprice_comments_error"); ?>"				
			},
			// custom error positions
			errorPlacement: function(error, element) {
				switch(element.attr("name")){					
					case 'sourceid':
						error.appendTo("#sourceid_error");
						break;	
					case 'datecollected':
						error.appendTo("#datecollected_error");
						break;	
					default:
						error.insertAfter(element);
						break;
				}
			}
		});
		
		// Replace every amount field having non numeric value with an empty string
		var nullprice = "<?php echo $config->price->nullamountsymbol; ?>";
		// alert(nullprice);		
		$(".numberfield").each(function(){
			if ($(this).val() == nullprice) {
				$(this).val('');
			}
			
		});
			
		// Copy buttons at the top to the bottom
		$("td.bottombuttons").html($("td.topbuttons").html());
		
	}); 
	// check that price is a valid number
	function IsValidAmount(value){
		var ValidChars = "0123456789";
		var valid=true;
		var Char;
		
		for (i = 0; i < value.length && valid == true; i++){ 
			Char = value.charAt(i); 
			if (ValidChars.indexOf(Char) == -1) {
				valid = false;
			}
		}
		return valid;
	}
</script>
<style>
table.formtable tr td, table.formtable tr td.label {
	vertical-align:middle;
}
input.smallnumberfield {
	width:150px;
}
select.chzn-select {
	min-width:180px;
}
</style>
<div class="pageinfo"><?php echo $this->translate("commodityprice_input_create_info"); ?></div>
<form id="priceform" action="<?php echo $posturl; ?>" method="post">
  <table class="formtable">
    <tfoot>
      <tr>
        <td class="topbuttons"><a href="<?php echo $this->baseUrl("inputproduction/list"); ?>">Cancel</a>&nbsp;&nbsp;
          <button type="submit" class="positiveaction save" name="save"><img src="<?php echo $this->baseUrl("images/tick.png"); ?>" /><?php echo $button_title_save; ?></button></td>
      </tr>
    </tfoot>
  </table>
  <br />
  <table class="formtable">
    <tr class="sectionheading bgrepeat">
      <td colspan="2"><?php echo $title; ?></td>
    </tr>
    <?php if ($sessionhaserror) { ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="error"><?php echo $session->getVar(ERROR_MESSAGE); ?></td>
    </tr>
    <?php } ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="pagedescription"><?php echo $this->translate("required_field_info"); ?>
        <input type="hidden" name="entityname" value="CommodityPriceSubmission" />
        <input type="hidden" name="status" id="status" value="Approved" />
        <input type="hidden" id="id" name="id" value="<?php echo encode($pricesubmission->getID()); ?>" /></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("commodityprice_datecollected_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
      <td><input type="text" name="datecollected" id="datecollected" class="datefield" value="<?php echo changemySQlDatetoPageFormat($pricesubmission->getDateCollected()); ?>" /><div id="datecollected_error"></div></td>
    </tr>
    <?php if($can_view_all) { ?>
    <tr>
      <td class="label"><?php echo $this->translate("commodityprice_input_location_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
      <td>
		<?php 
			$allinputsources = new LookupType(); 
			$allinputsources->setName("ALL_LGMIS_SOURCES");
			$price_sources = $allinputsources->getOptionValuesFromQuery();
			
			$input = new Zend_Form_Element_Select('sourceid',
								array(
									'multiOptions' => array_merge_maintain_keys(array('' => 'Select District'), $price_sources),								
									'view' => new Zend_View(),
									'decorators' => array('ViewHelper'),
									'class' => array("chzn-select")								
								)
							);
			$input->setValue($pricesubmission->getSourceID()); 
			echo $input->render(); 
           ?><div id="sourceid_error"></div>
      </td>
    </tr>
    <?php } else { ?>
        <input type="hidden" name="sourceid" id="sourceid" value="<?php echo $pricesubmission->getSourceID(); ?>" />            
    <?php } ?>
    <tr>
      <td class="label"><?php echo $this->translate("commodityprice_collectedby_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
      <td><?php echo $pricesubmission->getCollectedBy()->getName(); ?>
        <input type="hidden" name="collectedbyid" id="collectedbyid" value="<?php echo $pricesubmission->getCollectedByID(); ?>" /></td>
    </tr>
  </table>
  <br />
  <table class="formtable commodities">
    <thead>
      <tr class="sectionheading bgrepeat">
        <td align="left"><?php echo $this->translate("commodityprice_commodity_label"); ?></td>
        <td align="center" style="width:50px;"><?php echo $this->translate("commodityprice_units_label"); ?></td>
        <td align="center" style="width:100px;"><?php echo 'Wholesale'; ?></td>
        <td align="center" style="width:100px;"><?php echo 'Retail'; ?></td>        
        <td align="center" style="width:50px;">Notes</td>
      </tr>
    </thead>
    <?php
		$i = 0;		
		foreach($commodities as $commodity){
			// debugMessage($commodity);
			// if action is create, blank out any prices preset from previous submission			
			if(isEmptyString($pricesubmission->getID())){
				$commodity['wholesaleprice'] = "";
				$commodity['retailprice'] = "";
				$commodity['notes'] = "";
			}
  	?>
    <tr class="<?php echo $commodity['categoryid']; ?>">
      <td align="left" class="nowrapping"><?php echo $commodity['name']; ?>
        <input type="hidden" name="submissiondetails[<?php echo $i; ?>][commodityid]" id="submissiondetails_<?php echo $i; ?>_commodityid"  value="<?php echo $commodity['id']; ?>" />
        <input type="hidden" name="submissiondetails[<?php echo $i; ?>][pricecategoryid]" id="submissiondetails_<?php echo $i; ?>_pricecategoryid"  value="5" />
        <input type="hidden" name="submissiondetails[<?php echo $i; ?>][categoryid]" id="submissiondetails_<?php echo $i; ?>_categoryid"  value="<?php echo $commodity['categoryid']; ?>" class="<?php echo $commodity['categoryid']; ?>" /></td>
      <td align="center"><?php echo $commodity['units']; ?></td>
      <td align="center"><input type="text" name="submissiondetails[<?php echo $i; ?>][wholesaleprice]" id="submissiondetails_<?php echo $i; ?>_wholesaleprice" class="numberfield valid_price_<?php echo $i; ?>" value="<?php echo $commodity['wholesaleprice']; ?>" />
        <script>
			$(document).ready(function(){								
				$('#submissiondetails_<?php echo $i; ?>_wholesaleprice').rules("add", {wholesalelessthanretail: true});	
				
				// Add validation rules for prices on each line
				$.validator.addClassRules("valid_price_<?php echo $i; ?>", {
					validate_price_<?php echo $i; ?>: true				
				});
			
				// Validate the price amount
				$.validator.addMethod("validate_price_<?php echo $i; ?>", function(value, element) {				
					// only digits and numbers allowed
					if(!IsValidAmount(value)){
						return false;
					}
					return true;
				}, "<?php echo $this->translate("commodityprice_price_invalid_error");?>");	
				
				$("#notes_<?php echo $i; ?>_trigger").click(function(){					
					$("#dialog_<?php echo $i; ?>").dialog({
						width: 500,
						height: 200,
						show: 'slide',						
						modal: true,
						title: $(this).attr('title'),						
						buttons: [{text: "Ok", click: function() { $(this).dialog("close"); }}] 
					});
				});
				
				<?php if(isEmptyString($commodity['notes'])){ ?>
					$("#hasnote_<?php echo $i; ?>").hide();
					$("#nonote_<?php echo $i; ?>").show();	
				<?php } else { ?>
					$("#hasnote_<?php echo $i; ?>").show();
					$("#nonote_<?php echo $i; ?>").hide();
				<?php } ?>		
				
				$("#pricecomment_<?php echo $i; ?>").keyup(function(){
					// alert("notes have changed");
					$("#submissiondetails_<?php echo $i; ?>_notes").val($(this).val());
					
					if($("#submissiondetails_<?php echo $i; ?>_notes").val() == ''){ 
						$("#hasnote_<?php echo $i; ?>").hide();
						$("#nonote_<?php echo $i; ?>").show();	
					} else {
						$("#hasnote_<?php echo $i; ?>").show();
						$("#nonote_<?php echo $i; ?>").hide();
					}						
				});	
				
				
			});
		</script></td>
      <td align="center"><input type="text" name="submissiondetails[<?php echo $i; ?>][retailprice]" id="submissiondetails_<?php echo $i; ?>_retailprice" class="numberfield valid_price_<?php echo $i; ?>" value="<?php echo $commodity['retailprice']; ?>" /></td>
      <td align="center"><a href="javascript: doNothing();" class="notes" id="notes_<?php echo $i; ?>_trigger" title="Notes for <?php echo $commodity['name']; ?>"> <img id="nonote_<?php echo $i; ?>" class="hidden" src="<?php echo $this->baseUrl('images/notes.png'); ?>" /> <img id="hasnote_<?php echo $i; ?>" class="hidden" src="<?php echo $this->baseUrl('images/notes_plus.png'); ?>" /> </a>
        <input type="hidden" name="submissiondetails[<?php echo $i; ?>][notes]" id="submissiondetails_<?php echo $i; ?>_notes" value="<?php echo $commodity['notes']; ?>" />
        <div id="dialog_<?php echo $i; ?>" class="hidden" style="width:500px; height:250px;">
          <textarea class="expanding" style="width:450px" name="pricecomment_<?php echo $i; ?>" id="pricecomment_<?php echo $i; ?>"><?php echo $commodity['notes']; ?></textarea>
        </div></td>
    </tr>
    <?php $i++;
		}	
	?>
  </table>
  <br />
  <table class="formtable">
    <thead>
      <tr class="sectionheading">
        <td><?php echo $this->translate("commodityprice_comments_label"); ?>&nbsp;<?php echo $this->translate("required_field_marker"); ?></td>
      </tr>
    </thead>
    <tr>
      <td><textarea name="comments" id="comments" class="notesfield"><?php echo $pricesubmission->getComments(); ?></textarea></td>
    </tr>
  </table>
  <table class="formtable formactions">
    <tfoot>
      <tr>
        <td class="bottombuttons"></td>
      </tr>
    </tfoot>
  </table>
</form>
<?php
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
