Dear <?php echo $this->firstname; ?>,

 A request has been made for a new password for your account. You can get a new password by clicking on the link below:

<?php echo $this->serverUrl($this->url($this->resetpasswordurl))."\n"; ?>

If the page fails to open, copy the link and paste it in the address window of your browser. 

<?php echo $this->signoffname."\n"
	.$this->signoffemail."\n"
	.$this->serverUrl($this->baseUrl()); 
?>