<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
		$all_results_query = "SELECT 
			  d.datecollected AS datecollected,
			  cd.`name`,
			  FORMAT(ROUND(AVG(d.retailprice), -1), 0) AS `Retail Price`,
			  FORMAT(ROUND(AVG(d.wholesaleprice), -1), 0) AS `Wholesale Price`
			FROM
			  commoditypricedetails AS d 
			  INNER JOIN commodity cd ON d.`commodityid` = cd.`id`
			  INNER JOIN 
			    (SELECT 
			      MAX(cp.datecollected) AS datecollected
			    FROM
			      commoditypricedetails cp 
			      INNER JOIN commoditypricesubmission AS cs1 
			        ON (
			          cp.`submissionid` = cs1.`id` 
			          AND cs1.`status` = 'Approved'
			        ) 
			      INNER JOIN pricesource AS p 
			        ON (
			          cp.sourceid = p.id 
			          AND p.`applicationtype` = 0
			        ) 
			    WHERE cp.`pricecategoryid` = 4 AND cp.commodityid IN (95, 96, 97)
			    ) AS d2 
			    ON (
			      d.`datecollected` = d2.datecollected
			    ) 
			WHERE d.`pricecategoryid` = 4 AND d.commodityid IN (95, 96, 97)
			GROUP BY d.`commodityid`
			ORDER BY cd.name ";

		// debugMessage($all_results_query);
		$conn = Doctrine_Manager::connection(); 
		$result = $conn->fetchAll($all_results_query);
		// debugMessage($result); 
?>
	<b>As at <?php echo changeMySQLDateToPageFormat($result[0]['datecollected']); ?></b>
	<table class="list">
      <thead>
        <tr>
          <td>Fuel Type</td>
          <td>Price</td>
        </tr>
      </thead>
      <tbody>
        <?php 				  		
            	foreach($result as $line){							
            ?>
        <tr>
          <td><?php echo $line['name']; ?></td>
         
          <td align="right"><?php echo $line['Retail Price']; ?></td>
        </tr>
        <?php 						
            	} // end processing results 
            ?>
      </tbody>
    </table>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
