<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	# Page title
	$title = $this->translate("touristattraction_pagetitle_list");
	$this->headTitle($title);
	
	$can_view_all = true;
	if(isLGMISOfficial()) {
		$request->setParam('t'.HTML_TABLE_COLUMN_SEPARATOR.'districtid', $session->getVar('districtid')); 
		$district = new District();
		$district->populate($session->getVar('districtid'));
		$title = $district->getName()." Tourist Sites";
		$can_view_all = false;
	}
	
	# Create an instance of the class to handle the pagination
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("t.name"));
	$paginate->setDefaultSortBy("t.name");	
	$paginate->setFilterColumns(array("t.districtid","t.subcountyid"));

	$paginate->processPost($request->getParams());
	$all_results_query = "SELECT t.id, t.name AS `Name`, t.physicallocation AS `Physical Location`, t.contact AS `Contact`, sc.name AS `Sub-County`,  d.name as District  FROM touristattraction AS t INNER JOIN location d ON t.districtid = d.id LEFT JOIN location sc ON t.subcountyid = sc.id WHERE t.id <> '' ".$paginate->getSearchAndFilterSQL()." ".$paginate->getSortSQL();
	
	// debugMessage($all_results_query);
	$paginate->setItemCountFromSQLQuery($all_results_query);
	
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	// echo $current_results_query;
	$session->setVar(ALL_RESULTS_QUERY, $all_results_query);
	$session->setVar(CURRENT_RESULTS_QUERY, $current_results_query);
	# the query string to be appended to the return to list URL
	$session->setVar('list_query_string'.$request->getControllerName(), $request->getParams());
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
	# This variable stores the number of redundant columns returned in the query so that when we are printing
	# we are able to know how many columns to ignore. This variable is sent in the print URL
	$number_of_redundant_columns = 1;
	
	# the columns which contain numbers in the invoice query
	# Please note that the column count begins at 0
	$export_number_column_list = "";	
?>

<form action="<?php echo $this->baseUrl("touristattraction/listsearch"); ?>" method="get" id="usersform">
  <table class="filtercontainer">
    <tr>
      <td><table class="filtersection">
          <tr>
            <td>
            	<?php if($can_view_all) { ?>
					<?php
                        $districtlist = new LookupType(); 
                        $districtlist->setName("AVAILABLE_LGMIS_DISTRICTS");
                        $districtdropdown = new Zend_Form_Element_Select('ls'.HTML_TABLE_COLUMN_SEPARATOR.'locationid',
                                            array(
                                                'multiOptions' => array_merge_maintain_keys(array('' => 'All Districts'), $districtlist->getOptionValuesFromQuery()),								'view' => new Zend_View(),
                                                'decorators' => array('ViewHelper'),
                                                'class' => array('filterselect', 'chzn-select')
                                            )
                                        );
                        $districtdropdown->setValue($request->getParam('ls'.HTML_TABLE_COLUMN_SEPARATOR.'locationid')); 
                        echo $districtdropdown->render(); 
                      ?>
                <?php } ?>
            </td>
          </tr>
        </table></td>
      <td><table>
          <tr>
            <td><input class="filterselect" type="text" name="searchterm" id="searchterm" value="<?php echo $request->searchterm; ?>" title="Enter your search term here and click search" /></td>
          </tr>
          <tr>
            <td><button type="submit" class="positiveaction" id="searchbutton" title="Click here to Search or Filter"><img src="<?php echo $this->baseUrl("images/zoom_in.png"); ?>" alt="Search"/>Search</button></td>
          </tr>
        </table></td>
    </tr>
  </table>
  <?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
  <div class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
  <?php } ?>
  <?php // show a message that there are no items to display
	if ($has_no_data) {
?>
  <label class="error"><?php echo $this->translate("touristattraction_list_norecords"); ?></label>
  <?php } else { ?>
  <div id="counter"><?php echo sprintf($this->translate("touristattraction_list_counter"), $paginate->getItemCounterText()); ?></div>
  <div id="listcounter"><?php echo $this->listcountdropdown; ?></div>
  <div id="print"><a title="<?php echo $this->translate('global_print_as'); ?>" href="<?php echo $this->baseUrl('index/printerfriendly/'.EXPORT_NUMBER_COLUMN_LIST.'/'.$export_number_column_list.'/'.EXPORT_IGNORE_COLUMN_COUNT.'/'.$number_of_redundant_columns.'/'.PAGE_TITLE.'/'.$title); ?>" target="_blank"><?php echo $this->translate('global_print'); ?>&nbsp;<img src="<?php echo $this->baseUrl('images/printer.png'); ?>" alt="<?php echo $this->translate('global_print_as'); ?>" /></a></div>
  <?php if ($acl->checkPermission('Location Statistic', ACTION_EXPORT)) { ?>
  <div id="export"><a title="<?php echo $this->translate('global_export_as_excel'); ?>" href="<?php echo $this->baseUrl('index/exceldownload/'.EXPORT_NUMBER_COLUMN_LIST.'/'.$export_number_column_list.'/'.EXPORT_IGNORE_COLUMN_COUNT.'/'.$number_of_redundant_columns); ?>" target="_blank"><?php echo $this->translate('global_export_as'); ?>&nbsp;<img src="<?php echo $this->baseUrl('images/excel.png'); ?>" alt="<?php echo $this->translate('global_export_as_excel'); ?>" /></a></div>
  <?php } ?>
  <div id="listresults_div">
    <h2><?php echo $title; ?></h2>
    <table class="list">
      <thead>
        <tr>
          <?php if ($acl->checkPermission('Tourist Attraction', ACTION_EDIT)) {?>
          <td width="40">Edit</td>
          <?php } ?>
          <td><?php echo $paginate->getSortLinkForColumn('t.name','Name'); ?></td>
          <?php if($can_view_all) { ?>
          	<td width="100"><?php echo $paginate->getSortLinkForColumn('d.name', 'District'); ?></td>
          <?php } ?>
          <td width="150"><?php echo $paginate->getSortLinkForColumn('t.physicallocation','Physical Location'); ?></td>
          <td width="120"><?php echo $paginate->getSortLinkForColumn('t.Contact','Contact'); ?></td>
        </tr>
      </thead>
      <tbody>
        <?php 				  		
			foreach($result as $line){							
		?>
        <tr>
          <?php if ($acl->checkPermission('Tourist Attraction', ACTION_EDIT)) {?>
          <td class="nowrapping"><a href="<?php echo $this->baseUrl("touristattraction/index/id/".encode($line['id'])); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>"/></a></td>
          <?php } ?>
          <td class="nowrapping"><a href="<?php echo $this->baseUrl("touristattraction/view/id/".encode($line['id'])); ?>"><?php echo $line['Name']; ?></a></td>
         <?php if($can_view_all) { ?>
          <td class="nowrapping"><?php echo $line['District']; ?></td>
         <?php } ?>
          <td><?php echo $line['Physical Location']; ?></td>
          <td><?php echo $line['Contact']; ?></td>
        </tr>
        <?php } ?>
      </tbody>
    </table>
  </div>
  <?php	} ?>
  <div class="paginationlinks"><?php echo $paginate->getPaginationLinks(); ?></div>
</form>
<?php
	$session->setVar(SUCCESS_MESSAGE, "");
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
