<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = $this->translate("useraccount_pagetitle_changepassword");
	$this->headTitle($title); 
	$button_title = $this->translate("useraccount_button_edit_label");
	$posturl = $this->baseUrl("profile/edit");
		
	$useraccount = new UserAccount(); 	
	$useraccount->populate($userid);
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$useraccount->processPost($session->getVar(FORM_VALUES));	
	}	
?>
<style>
input[type="password"] {
	width:180px;
}
</style>
<script>
	$(document).ready(function() {		
		
		$.validator.addMethod("new_password_not_old", function(value, element) {
			var oldpass = $("#oldpassword").val();
			if(oldpass != "" && value == oldpass){
				return false;
			}		
			return true
		}, "New password should be different from current password");
	
	
		$("#changepasswordform").validate({		
			// define the validation rules one field at a time
			rules: {
				oldpassword: {
					required: true				
				},
				password: {
					required: true,
					new_password_not_old: true
				},
				confirmpassword: {
					required: true,
					equalTo: "#password"
				}				
			}, 
			// the messages for each of the fields being validated
			messages: {				
				oldpassword: {
					required: "<?php echo $this->translate("useraccount_oldpassword_error"); ?>"
				},
				password: {
					required: "<?php echo $this->translate("useraccount_password_error"); ?>"
				}, 
				confirmpassword: {
					required: "<?php echo $this->translate("useraccount_confirmpassword_error"); ?>",
					equalTo: "<?php echo $this->translate("useraccount_confirmpassword_error_equalto"); ?>"
				}
			}
		});
		
		$("#submit").click(function(){
			if($("#changepasswordform").valid()){
				if(window.confirm("Are you sure you want to change your Password. \n Click OK to proceed or Cancel to stay on current page")){
					$("#changepasswordform").submit();
				} else {
					return false;
				}
			} 
		});
	}); 
</script>
<div class="pageinfo"><?php echo $this->translate("useraccount_changepassword_info"); ?></div>
<form id="changepasswordform" action="<?php echo $posturl; ?>" method="post">
  <table class="formtable">
    <tr class="sectionheading">
      <td colspan="2"><?php echo $this->translate("useraccount_section_changepassword"); ?></td>
    </tr>
    <?php if ($sessionhaserror) { ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="error"><?php echo $session->getVar(ERROR_MESSAGE); ?></td>
    </tr>
    <?php } ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="pagedescription"><?php echo $this->translate("required_field_info"); ?></td>
    </tr>   
    <tr>
      <td class="label"><?php echo $this->translate("useraccount_password_current_label"); ?>: <?php echo $this->translate("required_field_marker"); ?></td>
      <td><input name="oldpassword" id="oldpassword" type="password" /></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("useraccount_password_new_label"); ?>: <?php echo $this->translate("required_field_marker"); ?></td>
      <td><input name="password" id="password" type="password" /></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("useraccount_password_confirm_label"); ?>: <?php echo $this->translate("required_field_marker"); ?></td>
      <td><input name="confirmpassword" id="confirmpassword" type="password" /></td>
    </tr>    
  </table>
  <table class="formtable formactions">
    <tfoot>
      <tr>
        <td><a href="<?php echo $this->baseUrl("profile/view"); ?>" class="negativeaction" title="Cancel Password Change"><img src="<?php echo $this->baseUrl("images/cross.png"); ?>" alt="Cancel Password Change" />&nbsp;Cancel</a>&nbsp;&nbsp;
        <button type="submit" class="positiveaction" id="submit" name="submit" title="Save New Password"><img src="<?php echo $this->baseUrl("images/tick.png"); ?>" alt="Save New Password" />&nbsp;Save Password</button>
        <input type="hidden" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($this->baseUrl("profile/changepasswordconfirmation")); ?>" />
        <input type="hidden" name="entityname" value="UserAccount" />
        <input type="hidden" id="id" name="id" value="<?php echo encode($useraccount->getID()); ?>" /></td>
      </tr>
    </tfoot>
  </table>
</form>
<?php
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>