<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	# Set page title
	$title = $this->translate("useraccount_pagetitle_changepassword_confirmation");
	$this->headTitle($title); 
	$logout_url = 'user/logout';
	if (isApplicationLGMIS()) {		
		$logout_url = 'lgmis/logout';
	}
?>
<div class="pageinfo"><?php echo $this->translate("useraccount_changepassword_info"); ?></div>
<table class="formtable">
    <tr class="sectionheading">
      <td colspan="2"><?php echo $this->translate("useraccount_section_changepassword"); ?></td>
    </tr>
	<tr>
    	<td><br /><br />
        	<label class="successmessage">You have sucessfully changed your password</label><br /><br />
            <a href="<?php echo $this->baseUrl($logout_url);?>">Click here</a> to login using your new password<br /><br />
        </td>
    </tr>
    </tr>
</table>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>