<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	$this->headTitle($this->translate("useraccount_pagetitle_recoverpassword_confirm"));
	
	$logout_url = 'user/logout';
	if (isApplicationLGMIS()) {		
		$logout_url = 'lgmis/logout';
	}
?>
<style>
#mainmenu, #header #headerright, #rightcolumn {
	display:none;
}
#contentcolumn {
	margin-top:25px;
}
</style>
<div class="pageinfo"><?php echo $this->translate("useraccount_recoverpassword_info"); ?></div>
<table class="formtable">
    <tr class="sectionheading">
      <td colspan="2"><?php echo $this->translate("useraccount_section_recoverpassword"); ?></td>
    </tr>
	<tr>
    	<td><br /><br />
        	<b>Note:</b>&nbsp;&nbsp;An email has been sent to you with details on how to reset your password. If you don't see the email in your inbox, please check your <b>Junk</b> or <b>Spam</b> mail folder.<br /><br />
Note that it may take a while for you to receive the activation email depending on your email service provider.
If you do not receive the email or have any other problems, let us know.<br /><br />
<a href="<?php echo $this->baseUrl($logout_url);?>">Click here</a> to login<br /><br />
        </td>
    </tr>
    </tr>
</table>   
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
