<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = $this->translate("useraccount_pagetitle_recoverpassword"); 
	$this->headTitle($title);

	$button_title = $this->translate("useraccount_button_recoverpassword");
	$posturl = $this->baseUrl("user/recoverpassword");
	
	$useraccount = new UserAccount(); 
	$useraccount->populate(decode($request->id));
	
	if ($sessionhaserror) {
		$formvalues = $session->getVar(FORM_VALUES); 
		$useraccount->setEmail($formvalues['email']); 
	}
?>
<style>
#mainmenu, #header #headerright, #rightcolumn {
	display:none;
}
#contentcolumn {
	margin-top:25px;
}
</style>
<script>
$(document).ready(function(){
	$("#recoverpasswordform").validate({
		rules: {
			email: {
				required: true,
				email: true
			}
		}, 
		messages: {
			email: {
				required: "<?php echo $this->translate("useraccount_email_error"); ?>",
				email: "<?php echo $this->translate("useraccount_email_invalid_error"); ?>"
			}
		}
	}); 
	
	<?php if(!isEmptyString($request->id)){ ?>
		// if admin user is resetting a user's password, automatically submit form.	 	
		$("#recoverpasswordform").submit();
	<?php } ?>
}); 
</script>
<form id="recoverpasswordform" action="<?php echo $posturl; ?>" method="post">
<?php if(isEmptyString($request->id)){ ?>
<div class="pageinfo"><?php echo $this->translate("useraccount_recoverpassword_info"); ?></div>
  <table class="formtable">
    <tr class="sectionheading">
      <td colspan="2"><?php echo $this->translate("useraccount_section_recoverpassword"); ?></td>
    </tr>
    <tr>
    	<td>&nbsp;</td>
    	<td>
		<?php if ($sessionhaserror) { ?>
            <?php echo $session->getVar(ERROR_MESSAGE); ?>
        <?php } else { ?>
            <br />
            An e-mail containing details on how to recover your password will be sent to the email address specified in your account<br /><br />  
	    <?php } ?>
        </td>  
    </tr>      
    <tr>
      <td class="label"><?php echo $this->translate("useraccount_email_label"); ?>: <?php echo $this->translate("required_field_marker"); ?></td>
      <td><input name="email" type="text" value="<?php echo $useraccount->getEmail(); ?>" /></td>
    </tr>    
  </table>
  <table class="formtable formactions">
    <tfoot>
      <tr>
      	<td width="150">&nbsp;</td>
        <td><a class="negativeaction" href="<?php echo $this->baseUrl('user/login'); ?>" title="Cancel Recover"><img src="<?php echo $this->baseUrl('images/cross.png'); ?>" /><?php echo $this->translate('global_button_cancel'); ?></a>&nbsp;&nbsp;
  <button type="submit" class="positiveaction" title="<?php echo $this->translate('useraccount_button_recoverpassword'); ?>"><img src="<?php echo $this->baseUrl('images/login.png'); ?>" /><?php echo $this->translate('useraccount_button_recoverpassword'); ?></button>      
        </td>
      </tr>
    </tfoot>
  </table>
  <?php } else{ ?>
  	<input type="hidden" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($this->baseUrl("profile/view/id/".encode($useraccount->getID()))); ?>" />
    <input type="hidden" name="<?php echo SUCCESS_MESSAGE; ?>" value="<?php echo "The password for '".$useraccount->getName()."' has been successfully reset and a message sent to their email address"; ?>" /> 
    <input type="hidden" name="email" value="<?php echo $useraccount->getEmail(); ?>" />   
    <div class="pageinfo" style="text-align:center;">Now reseting user's password... <br />Please wait...</div>
  <?php } ?>  
  <input type="hidden" name="entityname" value="UserAccount" />
</form>
<?php
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
