<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = $this->translate("useraccount_pagetitle_changepassword");
	$this->headTitle($title); 
		
	$useraccount = new UserAccount(); 
	$useraccount->populate(decode($request->id));
	
	#in case of errors in session, populate the fields from session
	if ($sessionhaserror) {
		$formvalues = $session->getVar(FORM_VALUES); 
		$useraccount->setEmail($formvalues['email']); 
	}
?>

<style>
input[type="password"] {
	width:180px;
}
#mainmenu, #header #headerright, #rightcolumn {
	display:none;
}
#contentcolumn {
	margin-top:25px;
}
</style>
<script>
	$(document).ready(function() {
		$("#resetpasswordform").validate({		
			// define the validation rules one field at a time
			rules: {
				password: {
					required: true
				},
				confirmpassword: {
					required: true,
					equalTo: "#password"
				}				
			}, 
			// the messages for each of the fields being validated
			messages: {				
				password: {
					required: "<?php echo $this->translate("useraccount_password_error"); ?>"
				}, 
				confirmpassword: {
					required: "<?php echo $this->translate("useraccount_confirmpassword_error"); ?>",
					equalTo: "<?php echo $this->translate("useraccount_confirmpassword_error_equalto"); ?>"
				}
			}
		});		
	}); 
</script>
<div class="pageinfo"><?php echo $this->translate("useraccount_resetpassword_info"); ?></div>
<form id="resetpasswordform" method="post" action="<?php echo $this->baseUrl("user/resetpassword"); ?>">
  <table class="formtable">
    <tr class="sectionheading">
      <td colspan="2"><?php echo $this->translate("useraccount_section_resetpassword"); ?></td>
    </tr>
    <?php if ($sessionhaserror) { ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="error"><?php echo $session->getVar(ERROR_MESSAGE); ?></td>
    </tr>
    <?php } ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="pagedescription"><?php echo $this->translate("required_field_info"); ?></td>
    </tr>   
    <tr>
      <td class="label"><?php echo $this->translate("useraccount_password_new_label"); ?>: <?php echo $this->translate("required_field_marker"); ?></td>
      <td><input name="password" id="password" type="password" /></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("useraccount_password_confirm_label"); ?>: <?php echo $this->translate("required_field_marker"); ?></td>
      <td><input name="confirmpassword" id="confirmpassword" type="password" /></td>
    </tr>    
  </table>
  <table class="formtable formactions">
    <tfoot>
      <tr>
        <td><a href="<?php echo $this->baseUrl("user/login"); ?>" class="negativeaction" title="Cancel Password Change"><img src="<?php echo $this->baseUrl("images/cross.png"); ?>" alt="Cancel Password Change" />&nbsp;Cancel</a>&nbsp;&nbsp;
        <button type="submit" class="positiveaction" id="submit" name="submit" title="Save New Password"><img src="<?php echo $this->baseUrl("images/tick.png"); ?>" alt="Save New Password" />&nbsp;Save Password</button>
        <input type="hidden" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($this->baseUrl("user/resetpasswordconfirmation")); ?>" />
        <input type="hidden" name="entityname" value="UserAccount" />
        <input type="hidden" id="id" name="id" value="<?php echo encode($useraccount->getID()); ?>" /></td>
      </tr>
    </tfoot>
  </table>
</form>
<?php
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
