<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	# Page title
	$title = $this->translate("contact_pagetitle_list");
	$this->headTitle($title);
	
	$can_view_all = true;
	if(isLGMISOfficial()) {
		$districtid = $session->getVar('districtid');
		$request->setParam('c'.HTML_TABLE_COLUMN_SEPARATOR.'locationid', $districtid); 
		$district = new District();
		$district->populate($districtid);
		$title = $district->getName()." Business Directory";
		$can_view_all = false;
	}	
	
	# Create an instance of the class to handle the pagination
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("c.firstname", "c.firstname", "c.othernames", "c.orgname", "c.phone", "c.address", "b.name"));
	$paginate->setFilterColumns(array("c.locationid","g.categoryid", "c.categoryid", "c.contacttype"));
	$paginate->setDefaultSortBy("c.firstname");	
	
	# define the letter to be clicked to ease navigation 
	$letter_query = "";	
	if (!isEmptyString($request->letter)){
		$letter_query = " AND (`c`.`orgname` LIKE '".$request->letter."%' OR `c`.`firstname` LIKE '".$request->letter."%') ";
	}
	
	$paginate->processPost($request->getParams());
	$all_results_query = "SELECT c.id, c.contacttype, if(contacttype = '1' , CONCAT(c.firstname,' ',c.lastname,' ',c.othernames), c.orgname) as `Name`, if(contacttype = '1' , 'Person','Company') as `Contact Type`, c.categoryid as categoryid, b.name as `Category`, c.phone as `Phone`, c.phone2 as `Alt Phone`, email as `Email`, address as `Address`, c.goodsorservicesoffered, group_concat(b.name separator ',') as `Sub Categories`  FROM contact c LEFT JOIN contactcategory g ON (g.contactid = c.id) LEFT JOIN businessdirectorycategory b ON (c.categoryid = b.id) WHERE c.id <> '' ".$paginate->getSearchAndFilterSQL()." GROUP BY c.id ".$letter_query."".$paginate->getSortSQL();
	
	// debugMessage($all_results_query);
	$paginate->setItemCountFromSQLQuery($all_results_query);
	
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	//echo $current_results_query;
	$session->setVar(ALL_RESULTS_QUERY, $all_results_query);
	$session->setVar(CURRENT_RESULTS_QUERY, $current_results_query);
	# the query string to be appended to the return to list URL
	$session->setVar('list_query_string'.$request->getControllerName(), $request->getParams());
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
	# This variable stores the number of redundant columns returned in the query so that when we are printing
	# we are able to know how many columns to ignore. This variable is sent in the print URL
	$number_of_redundant_columns = 2;
	
	# the columns which contain numbers in the invoice query
	# Please note that the column count begins at 0
	$export_number_column_list = "";
?>
<script>
	$(document).ready(function(){		
		// set hidden field for the alphabet and submit the form
		$(".alphabet").click(function(){
			var letter = $(this).attr('id');
			$('input#letter').val(letter);
			$("#searchbutton").click();
			return true;
		});
		
	}); 
</script>
<h2><?php echo $title; ?></h2>
<form action="<?php echo $this->baseUrl("contact/listsearch"); ?>" method="get" id="usersform">
  <table class="filtercontainer">
    <tr>
      <td><table class="filtersection">
          <tr>
            <td colspan="2"><?php
				$contacttype = new LookupType();
				$contacttype->setName("ALL_CONTACT_TYPES");				
				$type = new Zend_Form_Element_Select('c'.HTML_TABLE_COLUMN_SEPARATOR.'contacttype',
								array(
									'multiOptions' => array_merge_maintain_keys(array('' => 'All Types'), $contacttype->getOptionValuesAndDescription()),								
									'view' => new Zend_View(),
									'decorators' => array('ViewHelper'),
									'class' => array("filterselect", 'chzn-select'),
									'title' => 'Filter Contacts By Type'
								)
							);
				$type->setValue($request->getParam('c'.HTML_TABLE_COLUMN_SEPARATOR.'contacttype')); 				
				echo $type->render(); 
			  ?>
              &nbsp;&nbsp; <input type="hidden" name="<?php echo 'c'.HTML_TABLE_COLUMN_SEPARATOR.'categoryid'; ?>" id="<?php echo 'c'.HTML_TABLE_COLUMN_SEPARATOR.'categoryid'; ?>" value="<?php echo $request->getParam('c'.HTML_TABLE_COLUMN_SEPARATOR.'categoryid'); ?>" />
              <?php
				# lookup for business categories
				$categorylookup = new LookupType();
				$categorylookup->setName("ALL_BUSINESS_DIRECTORY_CATEGORIES");
				
				$cat = new Zend_Form_Element_Select('g'.HTML_TABLE_COLUMN_SEPARATOR.'categoryid',
								array(
									'multiOptions' => array_merge_maintain_keys(array('' => 'All Categories'), $categorylookup->getOptionValuesFromQuery()),								
									'view' => new Zend_View(),
									'decorators' => array('ViewHelper'),
									'class' => array("filterselect", 'chzn-select'),
									'title' => 'Filter Contacts By Category'
								)
							);
				$cat->setValue($request->getParam('g'.HTML_TABLE_COLUMN_SEPARATOR.'categoryid')); 				
				echo $cat->render(); 
			  ?></td>
          </tr>
          <tr>
          	<td colspan="3">
            <?php if($can_view_all) { ?>
				<?php
                    $districtlist = new LookupType(); 
                    $districtlist->setName("AVAILABLE_LGMIS_DISTRICTS");
                    $districtdropdown = new Zend_Form_Element_Select('c'.HTML_TABLE_COLUMN_SEPARATOR.'locationid',
                                        array(
                                            'multiOptions' => array_merge_maintain_keys(array('' => 'All Districts'), $districtlist->getOptionValuesFromQuery()),								'view' => new Zend_View(),
                                            'decorators' => array('ViewHelper'),
                                            'class' => array('filterselect', 'chzn-select')
                                        )
                                    );
                    $districtdropdown->setValue($request->getParam('c'.HTML_TABLE_COLUMN_SEPARATOR.'locationid')); 
                    echo $districtdropdown->render(); 
                  ?>
            <?php } ?>
            </td>
          </tr>
        </table></td>
      <td><table>
          <tr>
            <td><input class="filterselect" type="text" name="searchterm" id="searchterm" value="<?php echo $request->searchterm; ?>" title="Enter your search term here and click search" /></td>
          </tr>
          <tr>
            <td><button type="submit" class="positiveaction" id="searchbutton" title="Click here to Search or Filter"><img src="<?php echo $this->baseUrl("images/zoom_in.png"); ?>" alt="Search"/>Search</button>
            <input type="hidden" name="letter" id="letter" value="<?php echo $request->getParam('letter'); ?>" /></td>
          </tr>
        </table></td>
    </tr>
  </table>
  <?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
  <div class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
  <?php } ?>
  <?php // show a message that there are no items to display
	if ($has_no_data) {
?>
  <label class="error"><?php echo $this->translate("contact_list_norecords"); ?></label>
  <?php } else { ?>
  <div class="alphabetlist"><a href="<?php echo $this->baseUrl("lgmis/businesssector/id/".$request->id); ?>" title="View all the Contacts">All</a>&nbsp;&nbsp;|&nbsp;&nbsp;<?php echo $paginate->getAlphabetString(); ?></div>
  <div id="counter"><?php echo sprintf($this->translate("contact_list_counter"), $paginate->getItemCounterText()); ?></div>
  <div id="listcounter"><?php echo $this->listcountdropdown; ?></div>
  <div id="print"><a title="<?php echo $this->translate('global_print_as'); ?>" href="<?php echo $this->baseUrl('index/printerfriendly/'.EXPORT_NUMBER_COLUMN_LIST.'/'.$export_number_column_list.'/'.EXPORT_IGNORE_COLUMN_COUNT.'/'.$number_of_redundant_columns.'/'.PAGE_TITLE.'/'.$title); ?>" target="_blank"><?php echo $this->translate('global_print'); ?>&nbsp;<img src="<?php echo $this->baseUrl('images/printer.png'); ?>" alt="<?php echo $this->translate('global_print_as'); ?>" /></a></div>  
  <?php if ($acl->checkPermission('Contact', ACTION_EXPORT)) { ?>
  <div id="export"><a title="<?php echo $this->translate('global_export_as_excel'); ?>" href="<?php echo $this->baseUrl('index/exceldownload/'.EXPORT_NUMBER_COLUMN_LIST.'/'.$export_number_column_list.'/'.EXPORT_IGNORE_COLUMN_COUNT.'/'.$number_of_redundant_columns); ?>" target="_blank"><?php echo $this->translate('global_export_as'); ?>&nbsp;<img src="<?php echo $this->baseUrl('images/excel.png'); ?>" alt="<?php echo $this->translate('global_export_as_excel'); ?>" /></a></div>
  <?php } ?>
  <table style="width:700px;">
    <tr>
      <td vertical-align="top" style="height:200px;"><ul class="contactslist">
          <?php foreach($result as $line) { 
		  		$contact = new Contact();
				$contact->populate($line['id']);
				// $currentdistrict = $contact->getLocationID(); debugMessage($currentdistrict);
		  ?>          		
          <li>
            <h2><?php echo $line['Name']; ?></h2>
            <table class="list">
              <tbody>
                <tr>
                  <td><b>Phone:</b></td>
                  <td width="99%"><?php echo $line['Phone']; ?></td>
                </tr>
                <tr>
                  <td><b>Address:</b></td>
                  <td class="nowrapping"><?php echo nl2br($line['Address']); ?></b></td>
                </tr>
                <tr>
                    <td><b>Category: </b><br /><br />
                    <b>Tags: </b>
                    </td>
                    <td class="nowrapping">
					<?php echo $contact->getCategoryName(); ?></b><br /><br />
                    <?php echo $contact->getCategoryList(); ?>
                    </td>
                </tr>
				<tr>
                    <td colspan="2" class="nowrapping" style="height:80px;"><b>Goods/Services:</b><br />
                    <?php echo isEmptyString($line['goodsorservicesoffered']) ? '--' : $line['goodsorservicesoffered']; ?>
                    </td>
                </tr>
                <?php if ($acl->checkPermission('Contact', ACTION_EDIT) || $can_view_all || isLGMISOfficial()) { ?>
                <tr>
                  <td colspan="2">
                    <a href="<?php echo $this->baseUrl("contact/index/id/".encode($line['id'])); ?>" title="Update contact details"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>"/></a>&nbsp;
                    <a href="<?php echo $this->viewUrl(array("id" => encode($line['id']))); ?>" title="View contact details"><img src="<?php echo $this->baseUrl('images/contactview.jpg'); ?>"/></a>&nbsp;
                    </td>
                </tr>
                <?php } ?>
              </tbody>
            </table>
          </li>
          <?php 
               } // end processing results 
           ?>
        </ul></td>
    </tr>
  </table>
  <?php			
	} // end check that there are results    	
?>
  <div class="paginationlinks"><?php echo $paginate->getPaginationLinks(); ?></div>
</form>
<?php
	$session->setVar(SUCCESS_MESSAGE, "");
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
