<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$county = new County(); 
	
	// default title is to enable adding any payee
	$title = $this->translate("county_pagetitle_new"); 
	$posturl = $this->baseUrl("county/create");
	$button_title = $this->translate("county_button_new"); 
	
	// set the payee if provided in the url 
	if (!isEmptyString($request->id)) {
		$county->populate(decode($request->id));
		$title = sprintf($this->translate("county_pagetitle_edit"), $county->getName()); 
		$button_title = $this->translate("county_button_edit");
		$posturl = $this->baseUrl("county/edit"); 
	}
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$county->processPost($session->getVar(FORM_VALUES));	
	}
	
	$this->headTitle($title);  
?>
<script>
	$(document).ready(function() {
		$("#countyform").validate({		
			// define the validation rules one field at a time
			rules: {
				regionid: "required",
				districtid: "required",
				name: "required"
			}, 
			// the messages for each of the fields being validated
			messages: {				
				regionid: "<?php echo $this->translate("county_region_error"); ?>",
				districtid: "<?php echo $this->translate("county_district_error"); ?>",
				name: "<?php echo $this->translate("county_name_error"); ?>"
			}
		});

		// chained select to load the districts for a region
		$('#regionid').selectChain({
		    target: $('#districtid'),
		    url: '<?php echo $this->baseUrl('county/selectchain/'.SELECT_CHAIN_TYPE.'/region_districts/')?>',
		    data: 'currentvalue=<?php echo $county->getDistrictID(); ?>',
		    type: 'get'
		});
		$('#regionid').trigger("change"); 
		
	}); 
</script>

<div class="pageinfo"><?php echo $this->translate("county_page_info"); ?></div>
<form id="countyform" action="<?php echo $posturl; ?>" method="post">
  <table class="formtable">
    <tr class="sectionheading">
      <td colspan="2"><?php echo $title; ?></td>
    </tr>
    <?php if ($sessionhaserror) { ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="error"><?php echo $session->getVar(ERROR_MESSAGE); ?></td>
    </tr>
    <?php } ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="pagedescription"><?php echo $this->translate("required_field_info"); ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("county_region_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
      <td><?php
      	$regionlist = new LookupType(); 
      	$regionlist->setName("ALL_REGIONS");
       	$regiondropdown = new Zend_Form_Element_Select('regionid',
							array(
								'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $regionlist->getOptionValuesFromQuery()),								'view' => new Zend_View(),
								'decorators' => array('ViewHelper')
							)
						);
		$regiondropdown->setValue($county->getRegionID()); 
		echo $regiondropdown->render(); 
      ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("county_district_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
      <td><select name="districtid" id="districtid">
          <option value="">&lt;Select One&gt;</option>
        </select></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("county_name_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
      <td><input type="text" name="name" id="name" value="<?php echo $county->getName(); ?>" /></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("county_description_label"); ?>:</td>
      <td><textarea class="expanding" id="description" name="description"><?php echo $county->getDescription(); ?></textarea></td>
    </tr>
  </table>
  <table class="formtable formactions">
    <tfoot>
      <tr>
        <td><a href="<?php echo $this->baseUrl("dataentry"); ?>" title="Cancel">Cancel</a>&nbsp;&nbsp;
          <button type="submit" class="positiveaction" id="submit" name="submit" title="<?php echo $button_title; ?>"><img src="<?php echo $this->baseUrl("images/tick.png"); ?>" /><?php echo $button_title; ?></button>
          <input type="hidden" name="entityname" value="County" />
          <input type="hidden" id="id" name="id" value="<?php echo encode($county->getID()); ?>" /></td>
      </tr>
    </tfoot>
  </table>
</form>
<?php
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
