<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$county = new County();
	
	// default title is to enable adding any payee
	$title = $this->translate("county_pagetitle_view"); 
	$county->populate(decode($request->id));
	
	$this->headTitle($title);  
?>
<script>
	$(document).ready(function() {		
		$("table.formtable .delete").click(function(){
			if(window.confirm("Are you sure you want to Delete this County? \n Click OK to confirm or Cancel to stay on this page.")){
				return true;
			} else {
				return false;
			}
		}); 		
	}); 
</script>
<div class="pageinfo"><?php echo $this->translate("county_page_info"); ?></div>
<?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
<div class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
<?php } ?>
<table class="formtable">
  <tr class="sectionheading">
    <td colspan="2"><?php echo $title; ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("county_region_label"); ?>:</td>
    <td><?php echo $county->getRegion()->getName(); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("county_district_label"); ?>:</td>
    <td><?php echo $county->getDistrict()->getName(); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("county_name_label"); ?>:</td>
    <td><?php echo $county->getName(); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("county_description_label"); ?>:</td>
    <td><?php echo $county->getDescription(); ?></td>
  </tr> 
</table>
<table class="formtable formactions">
  <tfoot>
    <tr>
      <td><?php if ($acl->checkPermission('County', ACTION_DELETE) || isLGMISAdmin()) { ?>
        <a href="<?php echo $this->baseUrl('county/delete/entityname/County/id/'.encode($county->getID()).'/'.SUCCESS_MESSAGE.'/County has been successfully deleted/'.URL_SUCCESS.'/'.encode($this->baseUrl("county/list"))); ?>" class="negativeaction delete" title="<?php echo $this->translate("county_button_delete"); ?>"><img src="<?php echo $this->baseUrl('images/cross.png'); ?>" /><?php echo $this->translate("county_button_delete"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('County', ACTION_EDIT) || isLGMISAdmin()) { ?>
        <a href="<?php echo $this->baseUrl('county/index/id/'.encode($county->getID())); ?>" class="positiveaction" title="<?php echo $this->translate("county_pagetitle_edit"); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>" /><?php echo $this->translate("county_pagetitle_edit"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('County', ACTION_LIST) || isLGMISAdmin()) { ?>
        <a href="<?php echo $this->baseUrl('county/list'); ?>" class="positiveaction" title="<?php echo $this->translate("county_button_list"); ?>"><img src="<?php echo $this->baseUrl('images/arrow_undo.png'); ?>" /><?php echo $this->translate("county_button_list"); ?></a>
        <?php } ?></td>
    </tr>
  </tfoot>
</table>
<?php
	$session->setVar(SUCCESS_MESSAGE, "");
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
