<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$organisation = new Organisation();
	
	// default title is to enable adding any payee
	$title = $this->translate("organisation_pagetitle_view"); 
	$organisation->populate(decode($request->id));
	//$organisation->populate(3);	
	$this->headTitle($title);  
?>
<script>
	$(document).ready(function() {		
		$("table.formtable .delete").click(function(){
			if(window.confirm("Are you sure you want to Delete this Organisation? \n Click OK to confirm or Cancel to stay on this page.")){
				return true;
			} else {
				return false;
			}
		}); 		
	}); 
</script>

<div class="pageinfo"><?php echo $this->translate("organisation_page_info"); ?></div>
<?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
<div class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
<?php } ?>
<table class="formtable">
  <tr class="sectionheading">
    <td colspan="2"><?php echo $title; ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("organisation_name_label"); ?>:</td>
    <td><?php echo $organisation->getName(); ?></td>
  </tr>
  <tr>
      <td class="label"><?php echo $this->translate("organisation_abbreviation_label"); ?>:</td>
      <td><?php echo $organisation->getAbbreviation(); ?></td>
    </tr>
  <tr>
    <td class="label"><?php echo $this->translate("organisation_parentid_label"); ?>:</td>
    <td><?php 
	 		if(isEmptyString($organisation->getParentID())){
				echo "N/A"; 
			} else { 
	 			echo $organisation->getParent()->getName(); 
			}  
			
			?>
	 </td>
  </tr>
  
  <tr>
    <td class="label"><?php echo $this->translate("organisation_address_label"); ?>:</td>
    <td><?php echo $organisation->getAddress(); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("organisation_logo_label"); ?>:</td>
    <td><img src="<?php echo $this->baseUrl('uploads/lamis/logos/'.$organisation->getLogo()); ?>" /></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("organisation_phone_label"); ?>:</td>
    <td><?php echo $organisation->getPhone(); ?></td>
  </tr>
    <td class="label"><?php echo $this->translate("organisation_fax_label"); ?>:</td>
    <td><?php echo $organisation->getFax(); ?></td>
  </tr>
    <td class="label"><?php echo $this->translate("organisation_email_label"); ?>:</td>
    <td><?php echo $organisation->getEmail(); ?></td>
  </tr>
    <td class="label"><?php echo $this->translate("organisation_website_label"); ?>:</td>
    <td><?php echo $organisation->getWebsite(); ?></td>
  </tr>
  <tr><td class="label"><?php echo $this->translate("organisation_district_label");?></td>
  <td> <?php echo $organisation->displayDistrictsOfOperation(); ?>
  </td>
  </tr>
  
</table>

<table class="formtable">
  <tfoot>
    <tr>
      <td>	  	
        <?php if ($acl->checkPermission('Organisation', ACTION_DELETE)) { ?>
        <a href="<?php echo $this->baseUrl('organisation/delete/entityname/Organisation/id/'.encode($organisation->getID()).'/'.SUCCESS_MESSAGE.'/Organisation have been successfully deleted/'.URL_SUCCESS.'/'.encode($this->baseUrl("organisation/list"))); ?>" class="negativeaction delete" title="<?php echo $this->translate("organisation_button_delete"); ?>"><img src="<?php echo $this->baseUrl('images/cross.png'); ?>" /><?php echo $this->translate("organisation_button_delete"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('Organisation', ACTION_EDIT)) { ?>
        <a href="<?php echo $this->baseUrl('organisation/index/id/'.encode($organisation->getID())); ?>" class="positiveaction" title="<?php echo $this->translate("organisation_button_edit"); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>" /><?php echo $this->translate("organisation_button_edit"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('Organisation', ACTION_LIST)) { ?>
        <a href="<?php echo $this->baseUrl('organisation/list'); ?>" class="positiveaction" title="<?php echo $this->translate("organisation_button_list"); ?>"><img src="<?php echo $this->baseUrl('images/arrow_undo.png'); ?>" /><?php echo $this->translate("organisation_button_list"); ?></a>
        <?php } ?>
      </td>
    </tr>
  </tfoot>
</table>
<?php
	$session->setVar(SUCCESS_MESSAGE, "");
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
