<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$commodityunit = new CommodityUnit();
	
	// default title is to enable adding any payee
	$title = $this->translate("commodityunit_pagetitle_new"); 
	$posturl = $this->baseUrl("commodityunit/create");
	$button_title = $this->translate("commodityunit_button_new"); 
	
	// set the payee if provided in the url 
	if (!isEmptyString($request->id)) {
		$commodityunit->populate(decode($request->id));
		$title = sprintf($this->translate("commodityunit_pagetitle_edit"), $commodityunit->getName()); 
		$button_title = $this->translate("commodityunit_button_edit"); 
		$posturl = $this->baseUrl("commodityunit/edit");
	}
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$commodityunit->processPost($session->getVar(FORM_VALUES));	
	}
	
	$this->headTitle($title);  
?>
<script>
	$(document).ready(function() {
		$("#commodityunitform").validate({		
			// define the validation rules one field at a time
			rules: {
				name: "required" 
			}, 
			// the messages for each of the fields being validated
			messages: {				
				name: "<?php echo $this->translate("commodityunit_name_error"); ?>"
			}
		});
	}); 
</script>

<div class="pageinfo"><?php echo $this->translate("commodityunit_page_info"); ?></div>
<form id="commodityunitform" action="<?php echo $posturl; ?>" method="post">
  <table class="formtable">
    <tr class="sectionheading">
      <td colspan="2"><?php echo $title; ?></td>
    </tr>
    <?php if ($sessionhaserror) { ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="error"><?php echo $session->getVar(ERROR_MESSAGE); ?></td>
    </tr>
    <?php } ?>
    <tr>
      <td class="label">&nbsp;</td>
      <td class="pagedescription"><?php echo $this->translate("required_field_info"); ?></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("commodityunit_name_label"); ?>:<?php echo $this->translate("required_field_marker"); ?></td>
      <td><input type="text" name="name" id="name" value="<?php echo $commodityunit->getName(); ?>" /></td>
    </tr>
    <tr>
      <td class="label"><?php echo $this->translate("commodityunit_description_label"); ?>:</td>
      <td><textarea class="expanding" id="description" name="description"><?php echo $commodityunit->getDescription(); ?></textarea></td>
    </tr>
    <tr>
        <td class="label">Type:</td>
        <td><input type="radio" name="type" id="standard" class="<?php echo $commodityunit->isStandard() ? 1 : 0; ?>" value="1" />&nbsp;Standard
		<input type="radio" name="type" id="statistic" class="<?php echo $commodityunit->isStatistic() ? 1 : 0; ?>" value="2" />&nbsp;Statistic
        <input type="radio" name="type" id="cropinput" class="<?php echo $commodityunit->isCropInput() ? 1 : 0; ?>" value="3" />&nbsp;Crop Input
        <input type="radio" name="type" id="yield" class="<?php echo $commodityunit->isYieldMeasure() ? 1 : 0; ?>" value="4" />&nbsp;Yield Measure
        <input type="radio" name="type" id="livestock" class="<?php echo $commodityunit->isLiveStockMeasure() ? 1 : 0; ?>" value="5" />&nbsp;Livestock
        </td>
    </tr> 
  </table>
  <table class="formtable formactions">
    <tfoot>
      <tr>
        <td><a href="<?php echo $this->baseUrl("commodityunit/list"); ?>" title="Cancel">Cancel</a>&nbsp;&nbsp;
          <button type="submit" class="positiveaction" id="submit" name="submit"><img src="<?php echo $this->baseUrl("images/tick.png"); ?>" /><?php echo $button_title; ?></button>
          <input type="hidden" name="entityname" value="CommodityUnit" />
          <input type="hidden" id="id" name="id" value="<?php echo encode($commodityunit->getID()); ?>" /></td>
      </tr>
    </tfoot>
  </table>
</form>
<?php
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
