<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	# Page title
	$title = /*$this->translate("commodityunit_pagetitle_list")*/'Commodity and Resource Units';
	$this->headTitle($title);
	
	# Create an instance of the class to handle the pagination
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("u.name", "u.description"));
	$paginate->setFilterColumns(array("u.type"));
	$paginate->setDefaultSortBy("u.name");	
	$paginate->setItemCountPerPage("25");	

	$paginate->processPost($request->getParams());
	$all_results_query = "SELECT u.id, u.name as `Unit`, u.type as type, u.description as Description FROM commodityunit as u WHERE u.name <> '' ".$paginate->getSearchAndFilterSQL()." ".$paginate->getSortSQL();
	
	# debugMessage($all_results_query);
	$paginate->setItemCountFromSQLQuery($all_results_query);
	
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	//echo $current_results_query;
	$session->setVar(ALL_RESULTS_QUERY, $all_results_query);
	$session->setVar(CURRENT_RESULTS_QUERY, $current_results_query);
	# the query string to be appended to the return to list URL
	$session->setVar('list_query_string'.$request->getControllerName(), $request->getParams());
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
	# This variable stores the number of redundant columns returned in the query so that when we are printing
	# we are able to know how many columns to ignore. This variable is sent in the print URL
	$number_of_redundant_columns = 1;
	
	# the columns which contain numbers in the invoice query
	# Please note that the column count begins at 0
	$export_number_column_list = "";
?>

<form action="<?php echo $this->baseUrl("commodityunit/listsearch"); ?>" method="get" id="usersform">
  <table class="filtercontainer">
    <tr>
      <td><table class="filtersection">
          <tr>
            <td colspan="2">
				<?php					
					$typelistdropdown = new Zend_Form_Element_Select('u'.HTML_TABLE_COLUMN_SEPARATOR.'type',
										array(
											'multiOptions' => array('' => 'All Unit Types', '1' => 'Standard Measures', '2' => 'Statistic Measures', '3' => 'Crop Input Measures', '4' => 'Crop Yield Measures', '5' => 'Livestock Output Measures'),										
											'view' => new Zend_View(),
											'decorators' => array('ViewHelper'),
											'class' => array('filterselect', 'xchzn-select'),											
										)
									);
					$typelistdropdown->setValue($request->getParam('u'.HTML_TABLE_COLUMN_SEPARATOR.'type')); 
					echo $typelistdropdown->render(); 
				  ?></td>
          </tr>
        </table></td>
      <td><table>
          <tr>
            <td><input class="filterselect" type="text" name="searchterm" id="searchterm" value="<?php echo $request->searchterm; ?>" title="Enter your search term here and click search" /></td>
          </tr>
          <tr>
            <td><button type="submit" class="positiveaction" id="searchbutton" title="Click here to Search or Filter"><img src="<?php echo $this->baseUrl("images/zoom_in.png"); ?>" alt="Search"/>Search</button></td>
          </tr>
        </table></td>
    </tr>
  </table>
  <?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
  <div class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
  <?php } ?>
  <?php // show a message that there are no items to display
	if ($has_no_data) {
?>
  <label class="error"><?php echo $this->translate("commodityunit_list_norecords"); ?></label>
  <?php } else { ?>
  <div id="counter"><?php echo sprintf($this->translate("commodityunit_list_counter"), $paginate->getItemCounterText()); ?></div>
  <div id="listcounter"><?php echo $this->listcountdropdown; ?></div>
  <div id="print"><a title="<?php echo $this->translate('global_print_as'); ?>" href="<?php echo $this->baseUrl('index/printerfriendly/'.EXPORT_NUMBER_COLUMN_LIST.'/'.$export_number_column_list.'/'.EXPORT_IGNORE_COLUMN_COUNT.'/'.$number_of_redundant_columns.'/'.PAGE_TITLE.'/'.$title); ?>" target="_blank"><?php echo $this->translate('global_print'); ?>&nbsp;<img src="<?php echo $this->baseUrl('images/printer.png'); ?>" alt="<?php echo $this->translate('global_print_as'); ?>" /></a></div>
  <?php if ($acl->checkPermission('Commodity Unit', ACTION_EXPORT) || isLGMISAdmin()) { ?>
  <div id="export"><a title="<?php echo $this->translate('global_export_as_excel'); ?>" href="<?php echo $this->baseUrl('index/exceldownload/'.EXPORT_NUMBER_COLUMN_LIST.'/'.$export_number_column_list.'/'.EXPORT_IGNORE_COLUMN_COUNT.'/'.$number_of_redundant_columns); ?>" target="_blank"><?php echo $this->translate('global_export_as'); ?>&nbsp;<img src="<?php echo $this->baseUrl('images/excel.png'); ?>" alt="<?php echo $this->translate('global_export_as_excel'); ?>" /></a></div>
  <?php } ?>
  <div id="listresults_div">
    <h2><?php echo $title; ?></h2>
    <table class="list">
      <thead>
        <tr>
          <?php if ($acl->checkPermission('Commodity Unit', ACTION_EDIT) || isLGMISAdmin()) {?>
          <td width="15">Edit</td>
          <?php } ?>
          <td><?php echo $paginate->getSortLinkForColumn('name','Unit Name'); ?></td>
          <td width="200">Type</td>
          <td width="250">Description</td>
        </tr>
      </thead>
      <tbody>
        <?php 				  		
            	foreach($result as $line){							
            ?>
        <tr>
          <?php if ($acl->checkPermission('Commodity Unit', ACTION_EDIT) || isLGMISAdmin()) {?>
          <td><a href="<?php echo $this->baseUrl("commodityunit/index/id/".encode($line['id'])); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>"/></a></td>
          <?php } ?>
          <td><a href="<?php echo $this->baseUrl("commodityunit/view/id/".encode($line['id'])); ?>"><?php echo $line['Unit']; ?></a></td>
          <td>
			  <?php 
                $unittype = '';
                switch($line['type']){
                    case 2:
                        $unittype = 'Statistic Measure';
                        break;
                    case 3:
                        $unittype = 'Crop Input Measure';
                        break;
                    case 4:
                        $unittype = 'Yield Measure';
                        break;
					case 5:
						$unittype = 'Livestock Measure';
						break;
                    default:
                        $unittype = 'Standard Measure';
                        break;
                }
                echo $unittype;
              ?></td>
          <td><?php echo $line['Description']; ?></td>
        </tr>
        <?php } ?>
      </tbody>
        </tr>
      
    </table>
  </div>
  <?php			
	} // end check that there are results    	
?>
  <div class="paginationlinks"><?php echo $paginate->getPaginationLinks(); ?></div>
</form>
<?php
	$session->setVar(SUCCESS_MESSAGE, "");
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
