<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$commodityunit = new CommodityUnit();
	
	// default title is to enable adding any payee
	$title = $this->translate("commodityunit_pagetitle_view"); 
	$commodityunit->populate(decode($request->id));
		
	$this->headTitle($title);  
?>
<script>
	$(document).ready(function() {		
		$("table.formtable .delete").click(function(){
			if(window.confirm("Are you sure you want to Delete this Commodity Unit? \n Click OK to confirm or Cancel to stay on this page.")){
				return true;
			} else {
				return false;
			}
		}); 		
	}); 
</script>
<div class="pageinfo"><?php echo $this->translate("commodityunit_page_info"); ?></div>
<?php if(isNotAnEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
<div class="successmessage"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
<?php } ?>
<table class="formtable">
  <tr class="sectionheading">
    <td colspan="2"><?php echo $title; ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("commodityunit_name_label"); ?>:</td>
    <td><?php echo $commodityunit->getName(); ?></td>
  </tr>
  <tr>
    <td class="label"><?php echo $this->translate("commodityunit_description_label"); ?>:</td>
    <td><?php echo !isEmptyString($commodityunit->getDescription()) ? $commodityunit->getDescription() : '--'; ?></td>
  </tr>
  <tr>
    <td class="label">Type:</td>
    <td><?php echo $commodityunit->getTypeLabel(); ?></td>
  </tr>  
</table>
<table class="formtable formactions">
  <tfoot>
    <tr>
      <td><?php if ($acl->checkPermission('Commodity Unit', ACTION_DELETE) || isLGMISAdmin()) { ?>
        <a href="<?php echo $this->baseUrl('commodityunit/delete/entityname/CommodityUnit/id/'.encode($commodityunit->getID()).'/'.SUCCESS_MESSAGE.'/Commodity Unit has been successfully deleted/'.URL_SUCCESS.'/'.encode($this->baseUrl("commodityunit/list"))); ?>" class="negativeaction delete" title="<?php echo $this->translate("commodityunit_button_delete"); ?>"><img src="<?php echo $this->baseUrl('images/cross.png'); ?>" /><?php echo $this->translate("commodityunit_button_delete"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('Commodity Unit', ACTION_EDIT) || isLGMISAdmin()) { ?>
        <a href="<?php echo $this->baseUrl('commodityunit/index/id/'.encode($commodityunit->getID())); ?>" class="positiveaction" title="<?php echo $this->translate("commodityunit_button_edit"); ?>"><img src="<?php echo $this->baseUrl('images/edit.png'); ?>" /><?php echo $this->translate("commodityunit_button_edit"); ?></a>
        <?php } ?>
        <?php if ($acl->checkPermission('Commodity Unit', ACTION_LIST) || isLGMISAdmin()) { ?>
        <a href="<?php echo $this->baseUrl('commodityunit/list'); ?>" class="positiveaction" title="<?php echo $this->translate("commodityunit_button_list"); ?>"><img src="<?php echo $this->baseUrl('images/arrow_undo.png'); ?>" /><?php echo $this->translate("commodityunit_button_list"); ?></a>
        <?php } ?></td>
    </tr>
  </tfoot>
</table>
<?php
	$session->setVar(SUCCESS_MESSAGE, "");
	$clearsessionformvalues = true; 
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
